package linguistic;

import java.util.ArrayList;
import java.util.HashMap;

public class DBLookup {
	
	public static final String NOT_FOUND = "no definition found";
	
	/** Takes a query string in the form of
	 *    average-vb out-in
	 *    
	 *  
	 * @param queryString
	 * @return definition of the phrase
	 */
	public static String search(String queryString) {
		//System.out.println("Searching for == " + queryString);
		if (verbList.containsKey(queryString)) {
			return verbList.get(queryString);
		}
		return NOT_FOUND;
	}
	
	public static boolean isKnownParticle(String potential) {
		return particleList.contains(potential.toLowerCase());
	}
	
	/**
	 * List of particles to check against. Our POS tagger likes to tag these
	 * as adverbs, so we need to check this list to avoid false positives
	 */
	private static ArrayList<String> particleList = new ArrayList<String>();
	
	static {
		particleList.add("in");
		particleList.add("out");
		particleList.add("over");
		particleList.add("up");
		particleList.add("down");
		particleList.add("away");
		particleList.add("on");
		particleList.add("off");
		particleList.add("together");
		particleList.add("through");
		particleList.add("back");
		particleList.add("around");
		particleList.add("along");
		particleList.add("about");
		particleList.add("across");
		particleList.add("by");
		particleList.add("apart");
		particleList.add("thin");
		particleList.add("short");
		particleList.add("forth");
		particleList.add("behind");
		particleList.add("aside");
		particleList.add("home");
	}
	
	/**
	 * This is a placeholder for lookup up a search string in the database.
	 * 
	 * Until our verbs are in the db with definitions, I'm using
	 * this little hashmap.
	 */
	
	private static HashMap<String, String> verbList = new HashMap<String, String>();
	static {
		
		/** 
		 * Case 1: uninterrupted verb-prep 
		 * 		e.g. "back away" but not "back it away"
		 * 
		 **/
		verbList.put("take-vb x-nn in-in", "absorb, kinda");
		verbList.put("get-vb x-nn of-in", "what");
		verbList.put("keep-vb tabs-nn on-in", "track activity");
		verbList.put("act-vb up-in", "unk");
		verbList.put("add-vb up-in", "unk");
		verbList.put("air-vb out-in", "unk");
		verbList.put("amp-vb up-in", "unk");
		verbList.put("average-vb out-in", "unk");
		verbList.put("babble-vb on-in", "unk");
		verbList.put("back-vb away-in", "unk");
		verbList.put("back-vb down-in", "unk");
		verbList.put("back-vb off-in", "unk");
		verbList.put("back-vb out-in", "unk");
		verbList.put("back-vb up-in", "unk");
		verbList.put("band-vb together-in", "unk");
		verbList.put("black-vb out-in", "unk");
		verbList.put("blank-vb out-in", "unk");
		verbList.put("blast-vb off-in", "unk");
		verbList.put("blow-vb up-in", "unk");
		verbList.put("bog-vb down-in", "unk");
		verbList.put("boil-vb down-in", "unk");
		verbList.put("boil-vb over-in", "unk");
		verbList.put("boil-vb up-in", "unk");
		verbList.put("boot-vb up-in", "unk");
		verbList.put("bottom-vb out-in", "unk");
		verbList.put("bounce-vb back-in", "unk");
		verbList.put("bow-vb down-in", "unk");
		verbList.put("bow-vb out-in", "unk");
		verbList.put("branch-vb off-in", "unk");
		verbList.put("branch-vb out-in", "unk");
		verbList.put("break-vb down-in", "unk");
		verbList.put("break-vb in-in", "unk");
		verbList.put("break-vb off-in", "unk");
		verbList.put("break-vb open-in", "unk");
		verbList.put("break-vb out-in", "unk");
		verbList.put("break-vb through-in", "unk");
		verbList.put("break-vb up-in", "unk");
		verbList.put("bubble-vb over-in", "unk");
		verbList.put("bubble-vb up-in", "unk");
		verbList.put("build-vb on-in", "unk");
		verbList.put("build-vb up-in", "unk");
		verbList.put("bulk-vb up-in", "unk");
		verbList.put("bundle-vb up-in", "unk");
		verbList.put("burn-vb down-in", "unk");
		verbList.put("burn-vb off-in", "unk");
		verbList.put("burn-vb out-in", "unk");
		verbList.put("burn-vb up-in", "unk");
		verbList.put("burst-vb open-in", "unk");
		verbList.put("bust-vb open-in", "unk");
		verbList.put("bust-vb up-in", "unk");
		verbList.put("butt-vb in-in", "unk");
		verbList.put("button-vb up-in", "unk");
		verbList.put("call-vb back-in", "unk");
		verbList.put("call-vb out-in", "unk");
		verbList.put("calm-vb down-in", "unk");
		verbList.put("camp-vb out-in", "unk");
		verbList.put("cancel-vb out-in", "unk");
		verbList.put("carry-vb on-in", "unk");
		verbList.put("cast-vb off-in", "unk");
		verbList.put("catch-vb up-in", "unk");
		verbList.put("cave-vb in-in", "unk");
		verbList.put("chatter-vb on-in", "unk");
		verbList.put("check-vb in-in", "unk");
		verbList.put("check-vb out-in", "unk");
		verbList.put("cheer-vb up-in", "unk");
		verbList.put("chill-vb out-in", "unk");
		verbList.put("chime-vb in-in", "unk");
		verbList.put("choke-vb up-in", "unk");
		verbList.put("clam-vb up-in", "unk");
		verbList.put("clamp-vb down-in", "unk");
		verbList.put("clean-vb up-in", "unk");
		verbList.put("clear-vb off-in", "unk");
		verbList.put("clear-vb out-in", "unk");
		verbList.put("clear-vb up-in", "unk");
		verbList.put("cling-vb on-in", "unk");
		verbList.put("clock-vb in-in", "unk");
		verbList.put("clog-vb up-in", "unk");
		verbList.put("close-vb down-in", "unk");
		verbList.put("close-vb in-in", "unk");
		verbList.put("close-vb off-in", "unk");
		verbList.put("close-vb out-in", "unk");
		verbList.put("close-vb up-in", "unk");
		verbList.put("clown-vb around-in", "unk");
		verbList.put("coil-vb up-in", "unk");
		verbList.put("come-vb about-in", "unk");
		verbList.put("come-vb across-in", "unk");
		verbList.put("come-vb along-in", "unk");
		verbList.put("come-vb around-in", "unk");
		verbList.put("come-vb back-in", "unk");
		verbList.put("come-vb in-in", "unk");
		verbList.put("come-vb on-in", "unk");
		verbList.put("come-vb out-in", "unk");
		verbList.put("come-vb over-in", "unk");
		verbList.put("come-vb through-in", "unk");
		verbList.put("come-vb together-in", "unk");
		verbList.put("come-vb up-in", "unk");
		verbList.put("cool-vb down-in", "unk");
		verbList.put("cool-vb off-in", "unk");
		verbList.put("cotton-vb on-in", "unk");
		verbList.put("cough-vb up-in", "unk");
		verbList.put("crack-vb down-in", "unk");
		verbList.put("crack-vb open-in", "unk");
		verbList.put("crack-vb up-in", "unk");
		verbList.put("crop-vb up-in", "unk");
		verbList.put("cry-vb out-in", "unk");
		verbList.put("cut-vb back-in", "unk");
		verbList.put("cut-vb down-in", "unk");
		verbList.put("die-vb away-in", "unk");
		verbList.put("die-vb down-in", "unk");
		verbList.put("die-vb off-in", "unk");
		verbList.put("die-vb out-in", "unk");
		verbList.put("dig-vb in-in", "unk");
		verbList.put("divide-vb off-in", "unk");
		verbList.put("divide-vb up-in", "unk");
		verbList.put("double-vb up-in", "unk");
		verbList.put("drag-vb on-in", "unk");
		verbList.put("drag-vb out-in", "unk");
		verbList.put("draw-vb aside-in", "unk");
		verbList.put("draw-vb away-in", "unk");
		verbList.put("draw-vb back-in", "unk");
		verbList.put("dress-vb up-in", "unk");
		verbList.put("drift-vb off-in", "unk");
		verbList.put("drink-vb up-in", "unk");
		verbList.put("drive-vb around-in", "unk");
		verbList.put("drive-vb off-in", "unk");
		verbList.put("drive-vb up-in", "unk");
		verbList.put("drop-vb by-in", "unk");
		verbList.put("drop-vb in-in", "unk");
		verbList.put("drop-vb off-in", "unk");
		verbList.put("drop-vb out-in", "unk");
		verbList.put("dry-vb off-in", "unk");
		verbList.put("dry-vb out-in", "unk");
		verbList.put("dry-vb up-in", "unk");
		verbList.put("duck-vb out-in", "unk");
		verbList.put("ease-vb up-in", "unk");
		verbList.put("eat-vb in-in", "unk");
		verbList.put("eat-vb out-in", "unk");
		verbList.put("even-vb out-in", "unk");
		verbList.put("fess-vb up-in", "unk");
		verbList.put("fight-vb back-in", "unk");
		verbList.put("figure-vb in-in", "unk");
		verbList.put("fill-vb in-in", "unk");
		verbList.put("fill-vb out-in", "unk");
		verbList.put("find-vb out-in", "unk");
		verbList.put("finish-vb off-in", "unk");
		verbList.put("finish-vb up-in", "unk");
		verbList.put("firm-vb up-in", "unk");
		verbList.put("fit-vb in-in", "unk");
		verbList.put("flake-vb off-in", "unk");
		verbList.put("flare-vb up-in", "unk");
		verbList.put("flatten-vb out-in", "unk");
		verbList.put("flick-vb off-in", "unk");
		verbList.put("flick-vb on-in", "unk");
		verbList.put("flip-vb out-in", "unk");
		verbList.put("flunk-vb out-in", "unk");
		verbList.put("fly-vb off-in", "unk");
		verbList.put("fly-vb on-in", "unk");
		verbList.put("fly-vb over-in", "unk");
		verbList.put("follow-vb up-in", "unk");
		verbList.put("fool-vb around-in", "unk");
		verbList.put("fork-vb off-in", "unk");
		verbList.put("freak-vb out-in", "unk");
		verbList.put("freeze-vb up-in", "unk");
		verbList.put("freshen-vb up-in", "unk");
		verbList.put("fry-vb up-in", "unk");
		verbList.put("fuck-vb around-in", "unk");
		verbList.put("fuck-vb off-in", "unk");
		verbList.put("fuck-vb up-in", "unk");
		verbList.put("fumble-vb around-in", "unk");
		verbList.put("gas-vb up-in", "unk");
		verbList.put("gear-vb up-in", "unk");
		verbList.put("get-vb along-in", "unk");
		verbList.put("get-vb around-in", "unk");
		verbList.put("get-vb through-in", "unk");
		verbList.put("get-vb up-in", "unk");
		verbList.put("give-vb in-in", "unk");
		verbList.put("give-vb out-in", "unk");
		verbList.put("give-vb up-in", "unk");
		verbList.put("go-vb ahead-in", "unk");
		verbList.put("go-vb along-vb with-in", "unk");
		verbList.put("go-vb away-in", "unk");
		verbList.put("go-vb off-in", "unk");
		verbList.put("go-vb out-in", "unk");
		verbList.put("go-vb through-in", "unk");
		verbList.put("gray-vb out-in", "unk");
		verbList.put("grey-vb out-in", "unk");
		verbList.put("ground-vb out-in", "unk");
		verbList.put("grow-vb over-in", "unk");
		verbList.put("grow-vb up-in", "unk");
		verbList.put("hang-vb about-in", "unk");
		verbList.put("hang-vb around-in", "unk");
		verbList.put("hang-vb on-in", "unk");
		verbList.put("hang-vb out-in", "unk");
		verbList.put("hang-vb up-in", "unk");
		verbList.put("haul-vb off-in", "unk");
		verbList.put("head-vb off-in", "unk");
		verbList.put("head-vb on-in", "unk");
		verbList.put("head-vb out-in", "unk");
		verbList.put("help-vb out-in", "unk");
		verbList.put("hide-vb away-in", "unk");
		verbList.put("hide-vb out-in", "unk");
		verbList.put("hold-vb back-in", "unk");
		verbList.put("hold-vb off-in", "unk");
		verbList.put("hold-vb on-in", "unk");
		verbList.put("hold-vb out-in", "unk");
		verbList.put("hold-vb still-in", "unk");
		verbList.put("hold-vb up-in", "unk");
		verbList.put("hole-vb up-in", "unk");
		verbList.put("home-vb in-in", "unk");
		verbList.put("hook-vb up-in", "unk");
		verbList.put("hot-vb up-in", "unk");
		verbList.put("hunker-vb down-in", "unk");
		verbList.put("hurry-vb up-in", "unk");
		verbList.put("ice-vb over-in", "unk");
		verbList.put("jet-vb off-in", "unk");
		verbList.put("jump-vb up-in", "unk");
		verbList.put("keel-vb over-in", "unk");
		verbList.put("keep-vb up-in", "unk");
		verbList.put("kick-vb in-in", "unk");
		verbList.put("kick-vb off-in", "unk");
		verbList.put("kick-vb up-in", "unk");
		verbList.put("knot-vb up-in", "unk");
		verbList.put("knuckle-vb down-in", "unk");
		verbList.put("knuckle-vb under-in", "unk");
		verbList.put("lag-vb behind-in", "unk");
		verbList.put("lash-vb out-in", "unk");
		verbList.put("lay-vb down-in", "unk");
		verbList.put("lead-vb on-in", "unk");
		verbList.put("leave-vb off-in", "unk");
		verbList.put("let-vb go-in", "unk");
		verbList.put("let-vb out-in", "unk");
		verbList.put("let-vb up-in", "unk");
		verbList.put("level-vb off-in", "unk");
		verbList.put("level-vb out-in", "unk");
		verbList.put("lift-vb away-in", "unk");
		verbList.put("lift-vb off-in", "unk");
		verbList.put("lift-vb out-in", "unk");
		verbList.put("lift-vb up-in", "unk");
		verbList.put("light-vb up-in", "unk");
		verbList.put("line-vb out-in", "unk");
		verbList.put("line-vb up-in", "unk");
		verbList.put("link-vb up-in", "unk");
		verbList.put("listen-vb in-in", "unk");
		verbList.put("listen-vb up-in", "unk");
		verbList.put("lock-vb on-in", "unk");
		verbList.put("lock-vb up-in", "unk");
		verbList.put("log-vb in-in", "unk");
		verbList.put("log-vb off-in", "unk");
		verbList.put("log-vb on-in", "unk");
		verbList.put("log-vb out-in", "unk");
		verbList.put("look-vb around-in", "unk");
		verbList.put("look-vb on-in", "unk");
		verbList.put("look-vb up-in", "unk");
		verbList.put("lose-vb out-in", "unk");
		verbList.put("louse-vb up-in", "unk");
		verbList.put("make-vb up-in", "unk");
		verbList.put("match-vb up-in", "unk");
		verbList.put("meet-vb up-in", "unk");
		verbList.put("melt-vb down-in", "unk");
		verbList.put("mess-vb around-in", "unk");
		verbList.put("mess-vb up-in", "unk");
		verbList.put("mount-vb up-in", "unk");
		verbList.put("move-vb about-in", "unk");
		verbList.put("move-vb in-in", "unk");
		verbList.put("move-vb on-in", "unk");
		verbList.put("move-vb out-in", "unk");
		verbList.put("move-vb up-in", "unk");
		verbList.put("muddle-vb along-in", "unk");
		verbList.put("muddle-vb through-in", "unk");
		verbList.put("nose-vb around-in", "unk");
		verbList.put("open-vb up-in", "unk");
		verbList.put("opt-vb out-in", "unk");
		verbList.put("pack-vb up-in", "unk");
		verbList.put("parachute-vb in-in", "unk");
		verbList.put("patch-vb in-in", "unk");
		verbList.put("peter-vb out-in", "unk");
		verbList.put("phase-vb in-in", "unk");
		verbList.put("phase-vb out-in", "unk");
		verbList.put("pick-vb up-in", "unk");
		verbList.put("pig-vb out-in", "unk");
		verbList.put("pile-vb up-in", "unk");
		verbList.put("pipe-vb down-in", "unk");
		verbList.put("pipe-vb up-in", "unk");
		verbList.put("pluck-vb up-in", "unk");
		verbList.put("plug-vb in-in", "unk");
		verbList.put("poke-vb out-in", "unk");
		verbList.put("poke-vb up-in", "unk");
		verbList.put("polish-vb up-in", "unk");
		verbList.put("pop-vb down-in", "unk");
		verbList.put("pop-vb off-in", "unk");
		verbList.put("pop-vb out-in", "unk");
		verbList.put("pop-vb up-in", "unk");
		verbList.put("pour-vb down-in", "unk");
		verbList.put("pour-vb in-in", "unk");
		verbList.put("pour-vb off-in", "unk");
		verbList.put("pour-vb out-in", "unk");
		verbList.put("power-vb down-in", "unk");
		verbList.put("power-vb up-in", "unk");
		verbList.put("press-vb on-in", "unk");
		verbList.put("pull-vb apart-in", "unk");
		verbList.put("pull-vb away-in", "unk");
		verbList.put("pull-vb back-in", "unk");
		verbList.put("pull-vb in-in", "unk");
		verbList.put("pull-vb open-in", "unk");
		verbList.put("pull-vb out-in", "unk");
		verbList.put("pull-vb up-in", "unk");
		verbList.put("pump-vb in-in", "unk");
		verbList.put("pump-vb out-in", "unk");
		verbList.put("pump-vb up-in", "unk");
		verbList.put("push-vb back-in", "unk");
		verbList.put("push-vb forward-in", "unk");
		verbList.put("push-vb off-in", "unk");
		verbList.put("push-vb open-in", "unk");
		verbList.put("put-vb in-in", "unk");
		verbList.put("put-vb out-in", "unk");
		verbList.put("put-vb up-in", "unk");
		verbList.put("queue-vb up-in", "unk");
		verbList.put("rabbit-vb on-in", "unk");
		verbList.put("rack-vb up-in", "unk");
		verbList.put("ramp-vb up-in", "unk");
		verbList.put("rave-vb on-in", "unk");
		verbList.put("reach-vb out-in", "unk");
		verbList.put("rein-vb in-in", "unk");
		verbList.put("rest-vb up-in", "unk");
		verbList.put("rocket-vb up-in", "unk");
		verbList.put("roll-vb over-in", "unk");
		verbList.put("romp-vb around-in", "unk");
		verbList.put("root-vb around-in", "unk");
		verbList.put("run-vb around-in", "unk");
		verbList.put("run-vb back-in", "unk");
		verbList.put("run-vb out-in", "unk");
		verbList.put("run-vb over-in", "unk");
		verbList.put("rust-vb away-in", "unk");
		verbList.put("rust-vb in-in", "unk");
		verbList.put("rust-vb out-in", "unk");
		verbList.put("sack-vb out-in", "unk");
		verbList.put("saddle-vb up-in", "unk");
		verbList.put("scale-vb up-in", "unk");
		verbList.put("screw-vb up-in", "unk");
		verbList.put("seize-vb up-in", "unk");
		verbList.put("sell-vb out-in", "unk");
		verbList.put("set-vb off-in", "unk");
		verbList.put("set-vb out-in", "unk");
		verbList.put("set-vb up-in", "unk");
		verbList.put("settle-vb down-in", "unk");
		verbList.put("settle-vb in-in", "unk");
		verbList.put("shack-vb up-in", "unk");
		verbList.put("sharpen-vb up-in", "unk");
		verbList.put("shell-vb out-in", "unk");
		verbList.put("shine-vb out-in", "unk");
		verbList.put("ship-vb out-in", "unk");
		verbList.put("shop-vb around-in", "unk");
		verbList.put("short-vb out-in", "unk");
		verbList.put("shout-vb out-in", "unk");
		verbList.put("show-vb up-in", "unk");
		verbList.put("shut-vb down-in", "unk");
		verbList.put("shut-vb off-in", "unk");
		verbList.put("shut-vb up-in", "unk");
		verbList.put("shy-vb away-in", "unk");
		verbList.put("sign-vb off-in", "unk");
		verbList.put("sign-vb on-in", "unk");
		verbList.put("sign-vb up-in", "unk");
		verbList.put("silt-vb up-in", "unk");
		verbList.put("simmer-vb down-in", "unk");
		verbList.put("sink-vb in-in", "unk");
		verbList.put("sit-vb down-in", "unk");
		verbList.put("sit-vb up-in", "unk");
		verbList.put("skip-vb out-in", "unk");
		verbList.put("slack-vb off-in", "unk");
		verbList.put("slacken-vb off-in", "unk");
		verbList.put("sleep-vb in-in", "unk");
		verbList.put("slim-vb down-in", "unk");
		verbList.put("slough-vb off-in", "unk");
		verbList.put("slow-vb down-in", "unk");
		verbList.put("slow-vb up-in", "unk");
		verbList.put("smash-vb up-in", "unk");
		verbList.put("smooth-vb out-in", "unk");
		verbList.put("snap-vb in-in", "unk");
		verbList.put("snap-vb off-in", "unk");
		verbList.put("snuggle-vb down-in", "unk");
		verbList.put("snuggle-vb up-in", "unk");
		verbList.put("soak-vb in-in", "unk");
		verbList.put("soap-vb up-in", "unk");
		verbList.put("sober-vb up-in", "unk");
		verbList.put("soften-vb up-in", "unk");
		verbList.put("sound-vb off-in", "unk");
		verbList.put("speed-vb up-in", "unk");
		verbList.put("spill-vb out-in", "unk");
		verbList.put("spill-vb over-in", "unk");
		verbList.put("spin-vb around-in", "unk");
		verbList.put("spin-vb out-in", "unk");
		verbList.put("split-vb off-in", "unk");
		verbList.put("split-vb up-in", "unk");
		verbList.put("sprawl-vb out-in", "unk");
		verbList.put("spread-vb out-in", "unk");
		verbList.put("spring-vb up-in", "unk");
		verbList.put("spurt-vb out-in", "unk");
		verbList.put("squeeze-vb in-in", "unk");
		verbList.put("squeeze-vb out-in", "unk");
		verbList.put("stack-vb up-in", "unk");
		verbList.put("stand-vb in-in", "unk");
		verbList.put("stand-vb out-in", "unk");
		verbList.put("stand-vb up-in", "unk");
		verbList.put("start-vb off-in", "unk");
		verbList.put("start-vb out-in", "unk");
		verbList.put("start-vb over-in", "unk");
		verbList.put("start-vb up-in", "unk");
		verbList.put("stay-vb over-in", "unk");
		verbList.put("step-vb out-in", "unk");
		verbList.put("step-vb up-in", "unk");
		verbList.put("stick-vb around-in", "unk");
		verbList.put("stick-vb out-in", "unk");
		verbList.put("stick-vb up-in", "unk");
		verbList.put("stiffen-vb up-in", "unk");
		verbList.put("stock-vb up-in", "unk");
		verbList.put("stop-vb by-in", "unk");
		verbList.put("stop-vb in-in", "unk");
		verbList.put("stop-vb off-in", "unk");
		verbList.put("stop-vb over-in", "unk");
		verbList.put("straighten-vb out-in", "unk");
		verbList.put("straighten-vb up-in", "unk");
		verbList.put("stretch-vb out-in", "unk");
		verbList.put("stretch-vb over-in", "unk");
		verbList.put("strike-vb off-in", "unk");
		verbList.put("strike-vb out-in", "unk");
		verbList.put("stroll-vb along-in", "unk");
		verbList.put("sum-vb up-in", "unk");
		verbList.put("sweep-vb up-in", "unk");
		verbList.put("swell-vb up-in", "unk");
		verbList.put("switch-vb off-in", "unk");
		verbList.put("switch-vb on-in", "unk");
		verbList.put("tail-vb off-in", "unk");
		verbList.put("take-vb off-in", "unk");
		verbList.put("take-vb over-in", "unk");
		verbList.put("tank-vb up-in", "unk");
		verbList.put("taper-vb off-in", "unk");
		verbList.put("team-vb up-in", "unk");
		verbList.put("tear-vb off-in", "unk");
		verbList.put("tear-vb up-in", "unk");
		verbList.put("tee-vb off-in", "unk");
		verbList.put("tense-vb up-in", "unk");
		verbList.put("thin-vb out-in", "unk");
		verbList.put("throw-vb in-in", "unk");
		verbList.put("throw-vb up-in", "unk");
		verbList.put("tidy-vb up-in", "unk");
		verbList.put("tie-vb in-in", "unk");
		verbList.put("tighten-vb up-in", "unk");
		verbList.put("tip-vb over-in", "unk");
		verbList.put("tire-vb out-in", "unk");
		verbList.put("touch-vb down-in", "unk");
		verbList.put("towel-vb off-in", "unk");
		verbList.put("trace-vb back-in", "unk");
		verbList.put("trail-vb off-in", "unk");
		verbList.put("tuck-vb in-in", "unk");
		verbList.put("tune-vb in-in", "unk");
		verbList.put("tune-vb out-in", "unk");
		verbList.put("tune-vb up-in", "unk");
		verbList.put("turn-vb in-in", "unk");
		verbList.put("turn-vb off-in", "unk");
		verbList.put("turn-vb on-in", "unk");
		verbList.put("turn-vb out-in", "unk");
		verbList.put("turn-vb over-in", "unk");
		verbList.put("turn-vb up-in", "unk");
		verbList.put("usher-vb in-in", "unk");
		verbList.put("wake-vb up-in", "unk");
		verbList.put("walk-vb over-in", "unk");
		verbList.put("wander-vb off-in", "unk");
		verbList.put("wander-vb up-in", "unk");
		verbList.put("want-vb in-in", "unk");
		verbList.put("want-vb out-in", "unk");
		verbList.put("warm-vb up-in", "unk");
		verbList.put("wash-vb away-in", "unk");
		verbList.put("wash-vb down-in", "unk");
		verbList.put("wash-vb out-in", "unk");
		verbList.put("wash-vb up-in", "unk");
		verbList.put("watch-vb out-in", "unk");
		verbList.put("wear-vb away-in", "unk");
		verbList.put("wear-vb off-in", "unk");
		verbList.put("wear-vb on-in", "unk");
		verbList.put("wear-vb out-in", "unk");
		verbList.put("wear-vb thin-in", "unk");
		verbList.put("well-vb up-in", "unk");
		verbList.put("wheel-vb in-in", "unk");
		verbList.put("wheel-vb out-in", "unk");
		verbList.put("wind-vb down-in", "unk");
		verbList.put("wind-vb up-in", "unk");
		verbList.put("wipe-vb off-in", "unk");
		verbList.put("wipe-vb out-in", "unk");
		verbList.put("wipe-vb up-in", "unk");
		verbList.put("work-vb out-in", "unk");
		verbList.put("wrap-vb up-in", "unk");
		verbList.put("write-vb back-in", "unk");
		verbList.put("zone-vb out-in", "unk");

		/** 
		 * Case 2: interrupted verb-prep 
		 * 		e.g. break it open
		 * 
		 * Case 3: uninterrupted verb-prep (same as case 1)
		 * 		e.g. break open the safe 
		 **/
		verbList.put("act-vb x-nn out-in", "unk");
		verbList.put("add-vb x-nn in-in", "unk");
		verbList.put("add-vb x-nn on-in", "unk");
		verbList.put("add-vb x-nn up-in", "unk");
		verbList.put("air-vb x-nn out-in", "unk");
		verbList.put("amp-vb x-nn up-in", "unk");
		verbList.put("average-vb x-nn out-in", "unk");
		verbList.put("back-vb x-nn up-in", "unk");
		verbList.put("bail-vb x-nn out-in", "unk");
		verbList.put("balance-vb x-nn out-in", "unk");
		verbList.put("ball-vb x-nn up-in", "unk");
		verbList.put("band-vb x-nn together-in", "unk");
		verbList.put("bandage-vb x-nn up-in", "unk");
		verbList.put("bang-vb x-nn up-in", "unk");
		verbList.put("bat-vb x-nn away-in", "unk");
		verbList.put("bawl-vb x-nn out-in", "unk");
		verbList.put("beam-vb x-nn out-in", "unk");
		verbList.put("bear-vb x-nn out-in", "unk");
		verbList.put("beat-vb x-nn up-in", "unk");
		verbList.put("bed-vb x-nn down-in", "unk");
		verbList.put("belt-vb x-nn out-in", "unk");
		verbList.put("bite-vb x-nn out-in", "unk");
		verbList.put("black-vb x-nn out-in", "unk");
		verbList.put("blank-vb x-nn out-in", "unk");
		verbList.put("blast-vb x-nn away-in", "unk");
		verbList.put("blast-vb x-nn open-in", "unk");
		verbList.put("blast-vb x-nn out-in", "unk");
		verbList.put("bleep-vb x-nn out-in", "unk");
		verbList.put("block-vb x-nn off-in", "unk");
		verbList.put("block-vb x-nn out-in", "unk");
		verbList.put("blot-vb x-nn out-in", "unk");
		verbList.put("blow-vb x-nn away-in", "unk");
		verbList.put("blow-vb x-nn down-in", "unk");
		verbList.put("blow-vb x-nn off-in", "unk");
		verbList.put("blow-vb x-nn out-in", "unk");
		verbList.put("blow-vb x-nn up-in", "unk");
		verbList.put("blur-vb x-nn out-in", "unk");
		verbList.put("board-vb x-nn up-in", "unk");
		verbList.put("boil-vb x-nn down-in", "unk");
		verbList.put("bomb-vb x-nn out-in", "unk");
		verbList.put("book-vb x-nn up-in", "unk");
		verbList.put("boot-vb x-nn out-in", "unk");
		verbList.put("boot-vb x-nn up-in", "unk");
		verbList.put("bottle-vb x-nn in-in", "unk");
		verbList.put("bottle-vb x-nn up-in", "unk");
		verbList.put("bounce-vb x-nn back-in", "unk");
		verbList.put("bowl-vb x-nn over-in", "unk");
		verbList.put("box-vb x-nn in-in", "unk");
		verbList.put("box-vb x-nn up-in", "unk");
		verbList.put("break-vb x-nn down-in", "unk");
		verbList.put("break-vb x-nn in-in", "unk");
		verbList.put("break-vb x-nn off-in", "unk");
		verbList.put("break-vb x-nn open-in", "unk");
		verbList.put("break-vb x-nn out-in", "unk");
		verbList.put("break-vb x-nn up-in", "unk");
		verbList.put("brick-vb x-nn up-in", "unk");
		verbList.put("bring-vb x-nn about-in", "unk");
		verbList.put("bring-vb x-nn along-in", "unk");
		verbList.put("bring-vb x-nn down-in", "unk");
		verbList.put("bring-vb x-nn forth-in", "unk");
		verbList.put("bring-vb x-nn forward-in", "unk");
		verbList.put("bring-vb x-nn home-in", "unk");
		verbList.put("bring-vb x-nn in-in", "unk");
		verbList.put("bring-vb x-nn off-in", "unk");
		verbList.put("bring-vb x-nn over-in", "unk");
		verbList.put("bring-vb x-nn together-in", "unk");
		verbList.put("bring-vb x-nn up-in", "unk");
		verbList.put("brush-vb x-nn aside-in", "unk");
		verbList.put("brush-vb x-nn away-in", "unk");
		verbList.put("brush-vb x-nn off-in", "unk");
		verbList.put("buff-vb x-nn up-in", "unk");
		verbList.put("build-vb x-nn in-in", "unk");
		verbList.put("build-vb x-nn up-in", "unk");
		verbList.put("bump-vb x-nn off-in", "unk");
		verbList.put("bundle-vb x-nn up-in", "unk");
		verbList.put("buoy-vb x-nn up-in", "unk");
		verbList.put("burn-vb x-nn down-in", "unk");
		verbList.put("burn-vb x-nn off-in", "unk");
		verbList.put("burn-vb x-nn out-in", "unk");
		verbList.put("burn-vb x-nn up-in", "unk");
		verbList.put("burst-vb x-nn open-in", "unk");
		verbList.put("bus-vb x-nn in-in", "unk");
		verbList.put("bust-vb x-nn open-in", "unk");
		verbList.put("bust-vb x-nn up-in", "unk");
		verbList.put("button-vb x-nn down-in", "unk");
		verbList.put("button-vb x-nn up-in", "unk");
		verbList.put("buy-vb x-nn out-in", "unk");
		verbList.put("buy-vb x-nn up-in", "unk");
		verbList.put("call-vb x-nn back-in", "unk");
		verbList.put("call-vb x-nn off-in", "unk");
		verbList.put("call-vb x-nn out-in", "unk");
		verbList.put("call-vb x-nn up-in", "unk");
		verbList.put("calm-vb x-nn down-in", "unk");
		verbList.put("cancel-vb x-nn out-in", "unk");
		verbList.put("carry-vb x-nn away-in", "unk");
		verbList.put("carry-vb x-nn in-in", "unk");
		verbList.put("carry-vb x-nn on-in", "unk");
		verbList.put("carry-vb x-nn out-in", "unk");
		verbList.put("cart-vb x-nn away-in", "unk");
		verbList.put("carve-vb x-nn out-in", "unk");
		verbList.put("carve-vb x-nn up-in", "unk");
		verbList.put("cash-vb x-nn in-in", "unk");
		verbList.put("cast-vb x-nn down-in", "unk");
		verbList.put("cast-vb x-nn off-in", "unk");
		verbList.put("cast-vb x-nn out-in", "unk");
		verbList.put("cave-vb x-nn in-in", "unk");
		verbList.put("chalk-vb x-nn up-in", "unk");
		verbList.put("charge-vb x-nn up-in", "unk");
		verbList.put("chase-vb x-nn away-in", "unk");
		verbList.put("chase-vb x-nn down-in", "unk");
		verbList.put("chase-vb x-nn up-in", "unk");
		verbList.put("chat-vb x-nn up-in", "unk");
		verbList.put("check-vb x-nn in-in", "unk");
		verbList.put("check-vb x-nn out-in", "unk");
		verbList.put("cheer-vb x-nn on-in", "unk");
		verbList.put("cheer-vb x-nn up-in", "unk");
		verbList.put("chew-vb x-nn off-in", "unk");
		verbList.put("chew-vb x-nn out-in", "unk");
		verbList.put("chip-vb x-nn in-in", "unk");
		verbList.put("choke-vb x-nn off-in", "unk");
		verbList.put("choke-vb x-nn up-in", "unk");
		verbList.put("chop-vb x-nn down-in", "unk");
		verbList.put("chop-vb x-nn off-in", "unk");
		verbList.put("chop-vb x-nn up-in", "unk");
		verbList.put("churn-vb x-nn out-in", "unk");
		verbList.put("clean-vb x-nn out-in", "unk");
		verbList.put("clean-vb x-nn up-in", "unk");
		verbList.put("clear-vb x-nn away-in", "unk");
		verbList.put("clear-vb x-nn off-in", "unk");
		verbList.put("clear-vb x-nn out-in", "unk");
		verbList.put("clear-vb x-nn up-in", "unk");
		verbList.put("clog-vb x-nn up-in", "unk");
		verbList.put("close-vb x-nn down-in", "unk");
		verbList.put("close-vb x-nn in-in", "unk");
		verbList.put("close-vb x-nn off-in", "unk");
		verbList.put("close-vb x-nn out-in", "unk");
		verbList.put("close-vb x-nn up-in", "unk");
		verbList.put("clutter-vb x-nn up-in", "unk");
		verbList.put("code-vb x-nn up-in", "unk");
		verbList.put("coil-vb x-nn up-in", "unk");
		verbList.put("comb-vb x-nn out-in", "unk");
		verbList.put("conjure-vb x-nn up-in", "unk");
		verbList.put("contract-vb x-nn out-in", "unk");
		verbList.put("cook-vb x-nn up-in", "unk");
		verbList.put("cool-vb x-nn down-in", "unk");
		verbList.put("cool-vb x-nn off-in", "unk");
		verbList.put("coop-vb x-nn up-in", "unk");
		verbList.put("copy-vb x-nn down-in", "unk");
		verbList.put("copy-vb x-nn out-in", "unk");
		verbList.put("cough-vb x-nn up-in", "unk");
		verbList.put("count-vb x-nn out-in", "unk");
		verbList.put("cover-vb x-nn up-in", "unk");
		verbList.put("crack-vb x-nn open-in", "unk");
		verbList.put("crack-vb x-nn up-in", "unk");
		verbList.put("crank-vb x-nn out-in", "unk");
		verbList.put("crank-vb x-nn up-in", "unk");
		verbList.put("credit-vb x-nn back-in", "unk");
		verbList.put("crisp-vb x-nn up-in", "unk");
		verbList.put("cross-vb x-nn off-in", "unk");
		verbList.put("cross-vb x-nn out-in", "unk");
		verbList.put("crowd-vb x-nn out-in", "unk");
		verbList.put("curtain-vb x-nn off-in", "unk");
		verbList.put("cut-vb x-nn apart-in", "unk");
		verbList.put("cut-vb x-nn back-in", "unk");
		verbList.put("cut-vb x-nn down-in", "unk");
		verbList.put("cut-vb x-nn in-in", "unk");
		verbList.put("cut-vb x-nn off-in", "unk");
		verbList.put("cut-vb x-nn out-in", "unk");
		verbList.put("cut-vb x-nn short-in", "unk");
		verbList.put("cut-vb x-nn up-in", "unk");
		verbList.put("dam-vb x-nn up-in", "unk");
		verbList.put("damp-vb x-nn down-in", "unk");
		verbList.put("damp-vb x-nn out-in", "unk");
		verbList.put("deck-vb x-nn out-in", "unk");
		verbList.put("define-vb x-nn away-in", "unk");
		verbList.put("dial-vb x-nn in-in", "unk");
		verbList.put("dig-vb x-nn out-in", "unk");
		verbList.put("dig-vb x-nn up-in", "unk");
		verbList.put("dish-vb x-nn out-in", "unk");
		verbList.put("divide-vb x-nn off-in", "unk");
		verbList.put("divide-vb x-nn up-in", "unk");
		verbList.put("do-vb x-nn up-in", "unk");
		verbList.put("dole-vb x-nn out-in", "unk");
		verbList.put("doll-vb x-nn up-in", "unk");
		verbList.put("double-vb x-nn up-in", "unk");
		verbList.put("draft-vb x-nn in-in", "unk");
		verbList.put("drag-vb x-nn in-in", "unk");
		verbList.put("drag-vb x-nn on-in", "unk");
		verbList.put("drag-vb x-nn out-in", "unk");
		verbList.put("draw-vb x-nn aside-in", "unk");
		verbList.put("draw-vb x-nn away-in", "unk");
		verbList.put("draw-vb x-nn back-in", "unk");
		verbList.put("draw-vb x-nn forth-in", "unk");
		verbList.put("draw-vb x-nn up-in", "unk");
		verbList.put("dream-vb x-nn up-in", "unk");
		verbList.put("dredge-vb x-nn up-in", "unk");
		verbList.put("dress-vb x-nn up-in", "unk");
		verbList.put("drink-vb x-nn down-in", "unk");
		verbList.put("drink-vb x-nn up-in", "unk");
		verbList.put("drive-vb x-nn around-in", "unk");
		verbList.put("drive-vb x-nn away-in", "unk");
		verbList.put("drive-vb x-nn down-in", "unk");
		verbList.put("drive-vb x-nn home-in", "unk");
		verbList.put("drive-vb x-nn in-in", "unk");
		verbList.put("drive-vb x-nn off-in", "unk");
		verbList.put("drive-vb x-nn out-in", "unk");
		verbList.put("drive-vb x-nn up-in", "unk");
		verbList.put("drop-vb x-nn in-in", "unk");
		verbList.put("drop-vb x-nn off-in", "unk");
		verbList.put("drop-vb x-nn out-in", "unk");
		verbList.put("drown-vb x-nn out-in", "unk");
		verbList.put("dry-vb x-nn off-in", "unk");
		verbList.put("dry-vb x-nn out-in", "unk");
		verbList.put("dry-vb x-nn up-in", "unk");
		verbList.put("dump-vb x-nn out-in", "unk");
		verbList.put("ease-vb x-nn out-in", "unk");
		verbList.put("eat-vb x-nn up-in", "unk");
		verbList.put("eke-vb x-nn out-in", "unk");
		verbList.put("end-vb x-nn up-in", "unk");
		verbList.put("enter-vb x-nn in-in", "unk");
		verbList.put("etch-vb x-nn away-in", "unk");
		verbList.put("even-vb x-nn out-in", "unk");
		verbList.put("factor-vb x-nn in-in", "unk");
		verbList.put("fake-vb x-nn out-in", "unk");
		verbList.put("feed-vb x-nn in-in", "unk");
		verbList.put("fence-vb x-nn in-in", "unk");
		verbList.put("fend-vb x-nn off-in", "unk");
		verbList.put("ferret-vb x-nn out-in", "unk");
		verbList.put("ferry-vb x-nn in-in", "unk");
		verbList.put("figure-vb x-nn in-in", "unk");
		verbList.put("figure-vb x-nn out-in", "unk");
		verbList.put("fill-vb x-nn in-in", "unk");
		verbList.put("fill-vb x-nn out-in", "unk");
		verbList.put("filter-vb x-nn out-in", "unk");
		verbList.put("find-vb x-nn out-in", "unk");
		verbList.put("finish-vb x-nn off-in", "unk");
		verbList.put("finish-in", "unk");				//???
		verbList.put("fire-in", "unk");					//???
		verbList.put("firm-vb x-nn up-in", "unk");
		verbList.put("fish-vb x-nn out-in", "unk");
		verbList.put("fit-vb x-nn in-in", "unk");
		verbList.put("fix-vb x-nn up-in", "unk");
		verbList.put("flag-vb x-nn down-in", "unk");
		verbList.put("flake-vb x-nn off-in", "unk");
		verbList.put("flatten-vb x-nn out-in", "unk");
		verbList.put("flesh-vb x-nn out-in", "unk");
		verbList.put("flick-vb x-nn off-in", "unk");
		verbList.put("flick-vb x-nn on-in", "unk");
		verbList.put("fling-vb x-nn back-in", "unk");
		verbList.put("fling-vb x-nn off-in", "unk");
		verbList.put("fling-vb x-nn open-in", "unk");
		verbList.put("flush-vb x-nn out-in", "unk");
		verbList.put("fly-vb x-nn in-in", "unk");
		verbList.put("fog-vb x-nn up-in", "unk");
		verbList.put("follow-vb x-nn around-in", "unk");
		verbList.put("follow-vb x-nn up-in", "unk");
		verbList.put("fork-vb x-nn out-in", "unk");
		verbList.put("fork-vb x-nn over-in", "unk");
		verbList.put("frame-vb x-nn in-in", "unk");
		verbList.put("freak-vb x-nn out-in", "unk");
		verbList.put("free-vb x-nn up-in", "unk");
		verbList.put("frighten-vb x-nn off-in", "unk");
		verbList.put("fritter-vb x-nn away-in", "unk");
		verbList.put("fuck-vb x-nn up-in", "unk");
		verbList.put("gamble-vb x-nn away-in", "unk");
		verbList.put("gas-vb x-nn up-in", "unk");
		verbList.put("gather-vb x-nn up-in", "unk");
		verbList.put("gear-vb x-nn up-in", "unk");
		verbList.put("get-vb x-nn back-in", "unk");
		verbList.put("get-vb x-nn down-in", "unk");
		verbList.put("get-vb x-nn in-in", "unk");
		verbList.put("get-vb x-nn off-in", "unk");
		verbList.put("get-vb x-nn out-in", "unk");
		verbList.put("give-vb x-nn back-in", "unk");
		verbList.put("give-vb x-nn off-in", "unk");
		verbList.put("give-vb x-nn out-in", "unk");
		verbList.put("give-vb x-nn up-in", "unk");
		verbList.put("gnaw-vb x-nn away-in", "unk");
		verbList.put("gobble-vb x-nn up-in", "unk");
		verbList.put("gouge-vb x-nn away-in", "unk");
		verbList.put("gouge-vb x-nn out-in", "unk");
		verbList.put("grandfather-vb x-nn in-in", "unk");
		verbList.put("gray-vb x-nn out-in", "unk");
		verbList.put("grease-vb x-nn up-in", "unk");
		verbList.put("grey-vb x-nn out-in", "unk");
		verbList.put("grind-vb x-nn out-in", "unk");
		verbList.put("gulp-vb x-nn down-in", "unk");
		verbList.put("gun-vb x-nn down-in", "unk");
		verbList.put("gut-vb x-nn out-in", "unk");
		verbList.put("hack-vb x-nn up-in", "unk");
		verbList.put("hammer-vb x-nn out-in", "unk");
		verbList.put("hand-vb x-nn in-in", "unk");
		verbList.put("hand-vb x-nn off-in", "unk");
		verbList.put("hand-vb x-nn out-in", "unk");
		verbList.put("hand-vb x-nn over-in", "unk");
		verbList.put("hang-vb x-nn out-in", "unk");
		verbList.put("hang-vb x-nn up-in", "unk");
		verbList.put("harness-vb x-nn up-in", "unk");
		verbList.put("hash-vb x-nn out-in", "unk");
		verbList.put("haul-vb x-nn away-in", "unk");
		verbList.put("haul-vb x-nn in-in", "unk");
		verbList.put("haul-vb x-nn off-in", "unk");
		verbList.put("haul-vb x-nn out-in", "unk");
		verbList.put("haul-vb x-nn up-in", "unk");
		verbList.put("have-vb x-nn back-in", "unk");
		verbList.put("have-vb x-nn off-in", "unk");
		verbList.put("head-vb x-nn off-in", "unk");
		verbList.put("head-vb x-nn up-in", "unk");
		verbList.put("heat-vb x-nn up-in", "unk");
		verbList.put("heat-vb x-nn up-in", "unk");
		verbList.put("help-vb x-nn out-in", "unk");
		verbList.put("hem-vb x-nn in-in", "unk");
		verbList.put("hem-vb x-nn out-in", "unk");
		verbList.put("hew-vb x-nn out-in", "unk");
		verbList.put("hide-vb x-nn away-in", "unk");
		verbList.put("hike-vb x-nn up-in", "unk");
		verbList.put("hitch-vb x-nn up-in", "unk");
		verbList.put("hoist-vb x-nn up-in", "unk");
		verbList.put("hold-vb x-nn back-in", "unk");
		verbList.put("hold-vb x-nn down-in", "unk");
		verbList.put("hold-vb x-nn in-in", "unk");
		verbList.put("hold-vb x-nn off-in", "unk");
		verbList.put("hold-vb x-nn out-in", "unk");
		verbList.put("hold-vb x-nn up-in", "unk");
		verbList.put("hole-vb x-nn up-in", "unk");
		verbList.put("hollow-vb x-nn out-in", "unk");
		verbList.put("hook-vb x-nn up-in", "unk");
		verbList.put("hose-vb x-nn down-in", "unk");
		verbList.put("hunch-vb x-nn up-in", "unk");
		verbList.put("hunt-vb x-nn down-in", "unk");
		verbList.put("hunt-vb x-nn out-in", "unk");
		verbList.put("hunt-vb x-nn up-in", "unk");
		verbList.put("hurry-vb x-nn up-in", "unk");
		verbList.put("invite-vb x-nn in-in", "unk");
		verbList.put("invite-vb x-nn out-in", "unk");
		verbList.put("iron-vb x-nn out-in", "unk");
		verbList.put("isolate-vb x-nn out-in", "unk");
		verbList.put("jack-vb x-nn up-in", "unk");
		verbList.put("jam-vb x-nn up-in", "unk");
		verbList.put("jot-vb x-nn down-in", "unk");
		verbList.put("juggle-vb x-nn around-in", "unk");
		verbList.put("keep-vb x-nn out-in", "unk");
		verbList.put("keep-vb x-nn up-in", "unk");
		verbList.put("key-vb x-nn in-in", "unk");
		verbList.put("kick-vb x-nn in-in", "unk");
		verbList.put("kick-vb x-nn off-in", "unk");
		verbList.put("kick-vb x-nn out-in", "unk");
		verbList.put("kick-vb x-nn up-in", "unk");
		verbList.put("kill-vb x-nn off-in", "unk");
		verbList.put("kit-vb x-nn out-in", "unk");
		verbList.put("knock-vb x-nn off-in", "unk");
		verbList.put("knock-vb x-nn out-in", "unk");
		verbList.put("knock-vb x-nn over-in", "unk");
		verbList.put("knock-vb x-nn up-in", "unk");
		verbList.put("knot-vb x-nn up-in", "unk");
		verbList.put("lace-vb x-nn up-in", "unk");
		verbList.put("last-vb x-nn out-in", "unk");
		verbList.put("laugh-vb x-nn off-in", "unk");
		verbList.put("lay-vb x-nn off-in", "unk");
		verbList.put("lay-vb x-nn on-in", "unk");
		verbList.put("lay-vb x-nn out-in", "unk");
		verbList.put("lay-vb x-nn up-in", "unk");
		verbList.put("lead-vb x-nn on-in", "unk");
		verbList.put("leave-vb x-nn behind-in", "unk");
		verbList.put("leave-vb x-nn home-in", "unk");
		verbList.put("leave-vb x-nn in-in", "unk");
		verbList.put("leave-vb x-nn off-in", "unk");
		verbList.put("leave-vb x-nn open-in", "unk");
		verbList.put("leave-vb x-nn out-in", "unk");
		verbList.put("leave-vb x-nn over-in", "unk");
		verbList.put("let-vb x-nn down-in", "unk");
		verbList.put("let-vb x-nn in-in", "unk");
		verbList.put("let-vb x-nn off-in", "unk");
		verbList.put("let-vb x-nn out-in", "unk");
		verbList.put("level-vb x-nn off-in", "unk");
		verbList.put("level-vb x-nn out-in", "unk");
		verbList.put("lift-vb x-nn away-in", "unk");
		verbList.put("lift-vb x-nn off-in", "unk");
		verbList.put("lift-vb x-nn out-in", "unk");
		verbList.put("lift-vb x-nn up-in", "unk");
		verbList.put("light-vb x-nn up-in", "unk");
		verbList.put("like-vb x-nn back-in", "unk");
		verbList.put("limit-vb x-nn down-in", "unk");
		verbList.put("line-vb x-nn out-in", "unk");
		verbList.put("line-vb x-nn up-in", "unk");
		verbList.put("link-vb x-nn up-in", "unk");
		verbList.put("live-vb x-nn down-in", "unk");
		verbList.put("live-vb x-nn out-in", "unk");
		verbList.put("live-vb x-nn up-in", "unk");
		verbList.put("load-vb x-nn up-in", "unk");
		verbList.put("loan-vb x-nn out-in", "unk");
		verbList.put("lock-vb x-nn away-in", "unk");
		verbList.put("lock-vb x-nn down-in", "unk");
		verbList.put("lock-vb x-nn in-in", "unk");
		verbList.put("lock-vb x-nn on-in", "unk");
		verbList.put("lock-vb x-nn out-in", "unk");
		verbList.put("lock-vb x-nn up-in", "unk");
		verbList.put("log-vb x-nn in-in", "unk");
		verbList.put("log-vb x-nn off-in", "unk");
		verbList.put("log-vb x-nn on-in", "unk");
		verbList.put("log-vb x-nn out-in", "unk");
		verbList.put("look-vb x-nn over-in", "unk");
		verbList.put("look-vb x-nn up-in", "unk");
		verbList.put("lop-vb x-nn off-in", "unk");
		verbList.put("louse-vb x-nn up-in", "unk");
		verbList.put("lump-vb x-nn in-in", "unk");
		verbList.put("mail-vb x-nn back-in", "unk");
		verbList.put("mail-vb x-nn in-in", "unk");
		verbList.put("mail-vb x-nn out-in", "unk");
		verbList.put("make-vb x-nn out-in", "unk");
		verbList.put("make-vb x-nn up-in", "unk");
		verbList.put("map-vb x-nn out-in", "unk");
		verbList.put("march-vb x-nn off-in", "unk");
		verbList.put("mark-vb x-nn down-in", "unk");
		verbList.put("mark-vb x-nn off-in", "unk");
		verbList.put("mark-vb x-nn out-in", "unk");
		verbList.put("marry-vb x-nn off-in", "unk");
		verbList.put("mask-vb x-nn out-in", "unk");
		verbList.put("match-vb x-nn up-in", "unk");
		verbList.put("max-vb x-nn out-in", "unk");
		verbList.put("melt-vb x-nn down-in", "unk");
		verbList.put("mess-vb x-nn up-in", "unk");
		verbList.put("mete-vb x-nn out-in", "unk");
		verbList.put("miss-vb x-nn out-in", "unk");
		verbList.put("mix-vb x-nn up-in", "unk");
		verbList.put("mount-vb x-nn up-in", "unk");
		verbList.put("move-vb x-nn about-in", "unk");
		verbList.put("move-vb x-nn in-in", "unk");
		verbList.put("move-vb x-nn out-in", "unk");
		verbList.put("muddle-vb x-nn up-in", "unk");
		verbList.put("mush-vb x-nn together-in", "unk");
		verbList.put("nail-vb x-nn down-in", "unk");
		verbList.put("nail-vb x-nn up-in", "unk");
		verbList.put("narrow-vb x-nn down-in", "unk");
		verbList.put("nod-vb x-nn off-in", "unk");
		verbList.put("notch-vb x-nn up-in", "unk");
		verbList.put("note-vb x-nn down-in", "unk");
		verbList.put("nudge-vb x-nn up-in", "unk");
		verbList.put("open-vb x-nn up-in", "unk");
		verbList.put("pack-vb x-nn in-in", "unk");
		verbList.put("pack-vb x-nn up-in", "unk");
		verbList.put("parcel-vb x-nn out-in", "unk");
		verbList.put("pare-vb x-nn down-in", "unk");
		verbList.put("pare-vb x-nn off-in", "unk");
		verbList.put("pass-vb x-nn along-in", "unk");
		verbList.put("pass-vb x-nn off-in", "unk");
		verbList.put("pass-vb x-nn on-in", "unk");
		verbList.put("pass-vb x-nn over-in", "unk");
		verbList.put("patch-vb x-nn in-in", "unk");
		verbList.put("patch-vb x-nn up-in", "unk");
		verbList.put("pay-vb x-nn off-in", "unk");
		verbList.put("peel-vb x-nn off-in", "unk");
		verbList.put("pencil-vb x-nn in-in", "unk");
		verbList.put("phase-vb x-nn in-in", "unk");
		verbList.put("phase-vb x-nn out-in", "unk");
		verbList.put("pick-vb x-nn off-in", "unk");
		verbList.put("pick-vb x-nn out-in", "unk");
		verbList.put("pick-vb x-nn up-in", "unk");
		verbList.put("piece-vb x-nn together-in", "unk");
		verbList.put("pile-vb x-nn up-in", "unk");
		verbList.put("pin-vb x-nn down-in", "unk");
		verbList.put("pin-vb x-nn on-in", "unk");
		verbList.put("pin-vb x-nn up-in", "unk");
		verbList.put("pipe-vb x-nn in-in", "unk");
		verbList.put("piss-vb x-nn off-in", "unk");
		verbList.put("plant-vb x-nn out-in", "unk");
		verbList.put("pluck-vb x-nn out-in", "unk");
		verbList.put("pluck-vb x-nn up-in", "unk");
		verbList.put("plug-vb x-nn in-in", "unk");
		verbList.put("plunk-vb x-nn down-in", "unk");
		verbList.put("point-vb x-nn out-in", "unk");
		verbList.put("polish-vb x-nn off-in", "unk");
		verbList.put("polish-vb x-nn up-in", "unk");
		verbList.put("pop-vb x-nn off-in", "unk");
		verbList.put("pop-vb x-nn out-in", "unk");
		verbList.put("pop-vb x-nn up-in", "unk");
		verbList.put("pour-vb x-nn in-in", "unk");
		verbList.put("pour-vb x-nn off-in", "unk");
		verbList.put("pour-vb x-nn out-in", "unk");
		verbList.put("power-vb x-nn down-in", "unk");
		verbList.put("power-vb x-nn up-in", "unk");
		verbList.put("press-vb x-nn in-in", "unk");
		verbList.put("print-vb x-nn out-in", "unk");
		verbList.put("prop-vb x-nn open-in", "unk");
		verbList.put("prop-vb x-nn up-in", "unk");
		verbList.put("psyche-vb x-nn out-in", "unk");
		verbList.put("psyche-vb x-nn out-in", "unk");
		verbList.put("pucker-vb x-nn up-in", "unk");
		verbList.put("pull-vb x-nn across-in", "unk");
		verbList.put("pull-vb x-nn apart-in", "unk");
		verbList.put("pull-vb x-nn away-in", "unk");
		verbList.put("pull-vb x-nn back-in", "unk");
		verbList.put("pull-vb x-nn down-in", "unk");
		verbList.put("pull-vb x-nn in-in", "unk");
		verbList.put("pull-vb x-nn off-in", "unk");
		verbList.put("pull-vb x-nn open-in", "unk");
		verbList.put("pull-vb x-nn out-in", "unk");
		verbList.put("pull-vb x-nn up-in", "unk");
		verbList.put("pump-vb x-nn in-in", "unk");
		verbList.put("pump-vb x-nn out-in", "unk");
		verbList.put("pump-vb x-nn up-in", "unk");
		verbList.put("push-vb x-nn aside-in", "unk");
		verbList.put("push-vb x-nn away-in", "unk");
		verbList.put("push-vb x-nn back-in", "unk");
		verbList.put("push-vb x-nn down-in", "unk");
		verbList.put("push-vb x-nn forward-in", "unk");
		verbList.put("push-vb x-nn in-in", "unk");
		verbList.put("push-vb x-nn off-in", "unk");
		verbList.put("push-vb x-nn open-in", "unk");
		verbList.put("push-vb x-nn up-in", "unk");
		verbList.put("put-vb x-nn aside-in", "unk");
		verbList.put("put-vb x-nn away-in", "unk");
		verbList.put("put-vb x-nn back-in", "unk");
		verbList.put("put-vb x-nn by-in", "unk");
		verbList.put("put-vb x-nn down-in", "unk");
		verbList.put("put-vb x-nn in-in", "unk");
		verbList.put("put-vb x-nn off-in", "unk");
		verbList.put("put-vb x-nn on-in", "unk");
		verbList.put("put-vb x-nn out-in", "unk");
		verbList.put("put-vb x-nn through-in", "unk");
		verbList.put("put-vb x-nn together-in", "unk");
		verbList.put("put-vb x-nn up-in", "unk");
		verbList.put("puzzle-vb x-nn out-in", "unk");
		verbList.put("queue-vb x-nn up-in", "unk");
		verbList.put("rack-vb x-nn up-in", "unk");
		verbList.put("raise-vb x-nn up-in", "unk");
		verbList.put("ramp-vb x-nn up-in", "unk");
		verbList.put("ration-vb x-nn out-in", "unk");
		verbList.put("read-vb x-nn in-in", "unk");
		verbList.put("read-vb x-nn off-in", "unk");
		verbList.put("read-vb x-nn out-in", "unk");
		verbList.put("reel-vb x-nn in-in", "unk");
		verbList.put("reel-vb x-nn off-in", "unk");
		verbList.put("reel-vb x-nn out-in", "unk");
		verbList.put("rehash-vb x-nn out-in", "unk");
		verbList.put("rein-vb x-nn in-in", "unk");
		verbList.put("render-vb x-nn up-in", "unk");
		verbList.put("rent-vb x-nn out-in", "unk");
		verbList.put("ride-vb x-nn in-in", "unk");
		verbList.put("ride-vb x-nn out-in", "unk");
		verbList.put("ride-vb x-nn up-in", "unk");
		verbList.put("rig-vb x-nn up-in", "unk");
		verbList.put("ring-in", "unk");
		verbList.put("rinse-vb x-nn out-in", "unk");
		verbList.put("rip-vb x-nn off-in", "unk");
		verbList.put("rip-vb x-nn up-in", "unk");
		verbList.put("roar-vb x-nn out-in", "unk");
		verbList.put("roll-vb x-nn down-in", "unk");
		verbList.put("roll-vb x-nn out-in", "unk");
		verbList.put("roll-vb x-nn over-in", "unk");
		verbList.put("roll-vb x-nn up-in", "unk");
		verbList.put("root-vb x-nn out-in", "unk");
		verbList.put("rope-vb x-nn together-in", "unk");
		verbList.put("rough-vb x-nn in-in", "unk");
		verbList.put("rough-vb x-nn out-in", "unk");
		verbList.put("round-vb x-nn down-in", "unk");
		verbList.put("round-vb x-nn off-in", "unk");
		verbList.put("round-vb x-nn out-in", "unk");
		verbList.put("round-vb x-nn up-in", "unk");
		verbList.put("rub-vb x-nn in-in", "unk");
		verbList.put("rub-vb x-nn off-in", "unk");
		verbList.put("rub-vb x-nn out-in", "unk");
		verbList.put("rule-vb x-nn out-in", "unk");
		verbList.put("run-vb x-nn off-in", "unk");
		verbList.put("rush-vb x-nn out-in", "unk");
		verbList.put("saddle-vb x-nn up-in", "unk");
		verbList.put("sand-vb x-nn down-in", "unk");
		verbList.put("sand-vb x-nn off-in", "unk");
		verbList.put("scale-vb x-nn up-in", "unk");
		verbList.put("scar-vb x-nn up-in", "unk");
		verbList.put("scarf-vb x-nn down-in", "unk");
		verbList.put("schedule-vb x-nn in-in", "unk");
		verbList.put("schlep-vb x-nn around-in", "unk");
		verbList.put("scoop-vb x-nn out-in", "unk");
		verbList.put("scoop-vb x-nn up-in", "unk");
		verbList.put("scout-vb x-nn out-in", "unk");
		verbList.put("scrape-vb x-nn away-in", "unk");
		verbList.put("scrape-vb x-nn off-in", "unk");
		verbList.put("scrape-vb x-nn out-in", "unk");
		verbList.put("scrape-vb x-nn together-in", "unk");
		verbList.put("scrape-vb x-nn up-in", "unk");
		verbList.put("scratch-in", "unk");
		verbList.put("screen-vb x-nn out-in", "unk");
		verbList.put("screw-vb x-nn in-in", "unk");
		verbList.put("screw-vb x-nn up-in", "unk");
		verbList.put("scribble-vb x-nn down-in", "unk");
		verbList.put("scrub-vb x-nn off-in", "unk");
		verbList.put("scrub-vb x-nn out-in", "unk");
		verbList.put("scrunch-vb x-nn up-in", "unk");
		verbList.put("seal-vb x-nn in-in", "unk");
		verbList.put("seal-vb x-nn off-in", "unk");
		verbList.put("seal-vb x-nn out-in", "unk");
		verbList.put("seal-vb x-nn up-in", "unk");
		verbList.put("search-vb x-nn out-in", "unk");
		verbList.put("seek-vb x-nn out-in", "unk");
		verbList.put("sell-vb x-nn off-in", "unk");
		verbList.put("sell-vb x-nn out-in", "unk");
		verbList.put("send-vb x-nn back-in", "unk");
		verbList.put("send-vb x-nn in-in", "unk");
		verbList.put("send-vb x-nn off-in", "unk");
		verbList.put("send-vb x-nn out-in", "unk");
		verbList.put("separate-vb x-nn out-in", "unk");
		verbList.put("set-vb x-nn apart-in", "unk");
		verbList.put("set-vb x-nn aside-in", "unk");
		verbList.put("set-vb x-nn forth-in", "unk");
		verbList.put("set-vb x-nn off-in", "unk");
		verbList.put("set-vb x-nn up-in", "unk");
		verbList.put("settle-vb x-nn down-in", "unk");
		verbList.put("shack-vb x-nn up-in", "unk");
		verbList.put("shake-vb x-nn off-in", "unk");
		verbList.put("shake-vb x-nn out-in", "unk");
		verbList.put("shake-vb x-nn up-in", "unk");
		verbList.put("sharpen-vb x-nn up-in", "unk");
		verbList.put("shave-vb x-nn off-in", "unk");
		verbList.put("shell-vb x-nn out-in", "unk");
		verbList.put("ship-vb x-nn back-in", "unk");
		verbList.put("ship-vb x-nn out-in", "unk");
		verbList.put("shoo-vb x-nn away-in", "unk");
		verbList.put("shoot-vb x-nn down-in", "unk");
		verbList.put("shoot-vb x-nn off-in", "unk");
		verbList.put("shoot-vb x-nn up-in", "unk");
		verbList.put("shop-vb x-nn around-in", "unk");
		verbList.put("short-vb x-nn out-in", "unk");
		verbList.put("shout-vb x-nn back-in", "unk");
		verbList.put("shout-vb x-nn out-in", "unk");
		verbList.put("shovel-vb x-nn out-in", "unk");
		verbList.put("shrug-vb x-nn off-in", "unk");
		verbList.put("shut-vb x-nn down-in", "unk");
		verbList.put("shut-vb x-nn off-in", "unk");
		verbList.put("shut-vb x-nn out-in", "unk");
		verbList.put("shut-vb x-nn up-in", "unk");
		verbList.put("sign-vb x-nn up-in", "unk");
		verbList.put("single-vb x-nn out-in", "unk");
		verbList.put("sit-vb x-nn out-in", "unk");
		verbList.put("size-vb x-nn up-in", "unk");
		verbList.put("slam-vb x-nn down-in", "unk");
		verbList.put("slam-vb x-nn on-in", "unk");
		verbList.put("slap-vb x-nn down-in", "unk");
		verbList.put("slap-vb x-nn on-in", "unk");
		verbList.put("sleep-vb x-nn off-in", "unk");
		verbList.put("slice-vb x-nn off-in", "unk");
		verbList.put("slice-vb x-nn out-in", "unk");
		verbList.put("slice-vb x-nn up-in", "unk");
		verbList.put("slim-vb x-nn down-in", "unk");
		verbList.put("slip-vb x-nn in-in", "unk");
		verbList.put("slip-vb x-nn off-in", "unk");
		verbList.put("slip-vb x-nn on-in", "unk");
		verbList.put("slough-vb x-nn off-in", "unk");
		verbList.put("slow-vb x-nn down-in", "unk");
		verbList.put("slug-vb x-nn down-in", "unk");
		verbList.put("slurp-vb x-nn up-in", "unk");
		verbList.put("smash-vb x-nn in-in", "unk");
		verbList.put("smash-vb x-nn up-in", "unk");
		verbList.put("smooth-vb x-nn away-in", "unk");
		verbList.put("smooth-vb x-nn out-in", "unk");
		verbList.put("smuggle-vb x-nn in-in", "unk");
		verbList.put("smuggle-vb x-nn out-in", "unk");
		verbList.put("snap-vb x-nn in-in", "unk");
		verbList.put("snap-vb x-nn off-in", "unk");
		verbList.put("snap-vb x-nn up-in", "unk");
		verbList.put("snatch-vb x-nn up-in", "unk");
		verbList.put("sniff-vb x-nn out-in", "unk");
		verbList.put("soak-vb x-nn in-in", "unk");
		verbList.put("soak-vb x-nn up-in", "unk");
		verbList.put("soap-vb x-nn up-in", "unk");
		verbList.put("sober-vb x-nn up-in", "unk");
		verbList.put("sock-vb x-nn in-in", "unk");
		verbList.put("soften-vb x-nn up-in", "unk");
		verbList.put("sop-vb x-nn up-in", "unk");
		verbList.put("sort-vb x-nn out-in", "unk");
		verbList.put("sound-vb x-nn out-in", "unk");
		verbList.put("space-vb x-nn out-in", "unk");
		verbList.put("spark-vb x-nn off-in", "unk");
		verbList.put("speed-vb x-nn up-in", "unk");
		verbList.put("spell-vb x-nn out-in", "unk");
		verbList.put("spin-vb x-nn out-in", "unk");
		verbList.put("spirit-vb x-nn away-in", "unk");
		verbList.put("spit-vb x-nn out-in", "unk");
		verbList.put("split-vb x-nn off-in", "unk");
		verbList.put("split-vb x-nn up-in", "unk");
		verbList.put("spread-vb x-nn out-in", "unk");
		verbList.put("spruce-vb x-nn up-in", "unk");
		verbList.put("spur-vb x-nn on-in", "unk");
		verbList.put("square-vb x-nn away-in", "unk");
		verbList.put("square-vb x-nn up-in", "unk");
		verbList.put("squeeze-vb x-nn in-in", "unk");
		verbList.put("squeeze-vb x-nn out-in", "unk");
		verbList.put("squirrel-vb x-nn away-in", "unk");
		verbList.put("stack-vb x-nn up-in", "unk");
		verbList.put("stall-vb x-nn off-in", "unk");
		verbList.put("stamp-vb x-nn on-in", "unk");
		verbList.put("stamp-vb x-nn out-in", "unk");
		verbList.put("stand-vb x-nn up-in", "unk");
		verbList.put("start-vb x-nn off-in", "unk");
		verbList.put("start-vb x-nn out-in", "unk");
		verbList.put("start-vb x-nn over-in", "unk");
		verbList.put("start-vb x-nn up-in", "unk");
		verbList.put("stash-vb x-nn away-in", "unk");
		verbList.put("stave-vb x-nn off-in", "unk");
		verbList.put("steal-vb x-nn away-in", "unk");
		verbList.put("steam-vb x-nn open-in", "unk");
		verbList.put("step-vb x-nn up-in", "unk");
		verbList.put("stick-vb x-nn out-in", "unk");
		verbList.put("stick-vb x-nn up-in", "unk");
		verbList.put("stiffen-vb x-nn up-in", "unk");
		verbList.put("stink-vb x-nn up-in", "unk");
		verbList.put("stir-vb x-nn in-in", "unk");
		verbList.put("stir-vb x-nn up-in", "unk");
		verbList.put("store-vb x-nn up-in", "unk");
		verbList.put("straighten-vb x-nn out-in", "unk");
		verbList.put("straighten-vb x-nn up-in", "unk");
		verbList.put("strap-vb x-nn up-in", "unk");
		verbList.put("strike-vb x-nn down-in", "unk");
		verbList.put("strike-vb x-nn off-in", "unk");
		verbList.put("strike-vb x-nn out-in", "unk");
		verbList.put("strip-vb x-nn off-in", "unk");
		verbList.put("stub-vb x-nn out-in", "unk");
		verbList.put("suck-vb x-nn in-in", "unk");
		verbList.put("suck-vb x-nn out-in", "unk");
		verbList.put("suck-vb x-nn up-in", "unk");
		verbList.put("sum-vb x-nn up-in", "unk");
		verbList.put("summon-vb x-nn up-in", "unk");
		verbList.put("swallow-vb x-nn down-in", "unk");
		verbList.put("swallow-vb x-nn up-in", "unk");
		verbList.put("swear-vb x-nn in-in", "unk");
		verbList.put("sweat-vb x-nn off-in", "unk");
		verbList.put("sweat-vb x-nn out-in", "unk");
		verbList.put("sweep-vb x-nn away-in", "unk");
		verbList.put("sweep-vb x-nn up-in", "unk");
		verbList.put("switch-vb x-nn off-in", "unk");
		verbList.put("switch-vb x-nn on-in", "unk");
		verbList.put("swoop-vb x-nn up-in", "unk");
		verbList.put("tack-vb x-nn on-in", "unk");
		verbList.put("tack-vb x-nn up-in", "unk");
		verbList.put("take-vb x-nn aback-in", "unk");
		verbList.put("take-vb x-nn along-in", "unk");
		verbList.put("take-vb x-nn apart-in", "unk");
		verbList.put("take-vb x-nn away-in", "unk");
		verbList.put("take-vb x-nn back-in", "unk");
		verbList.put("take-vb x-nn down-in", "unk");
		verbList.put("take-vb x-nn home-in", "unk");
		verbList.put("take-vb x-nn in-in", "unk");
		verbList.put("take-vb x-nn off-in", "unk");
		verbList.put("take-vb x-nn on-in", "unk");
		verbList.put("take-vb x-nn out-in", "unk");
		verbList.put("take-vb x-nn over-in", "unk");
		verbList.put("take-vb x-nn up-in", "unk");
		verbList.put("talk-vb x-nn over-in", "unk");
		verbList.put("tangle-vb x-nn up-in", "unk");
		verbList.put("tank-vb x-nn up-in", "unk");
		verbList.put("tap-vb x-nn off-in", "unk");
		verbList.put("tear-vb x-nn apart-in", "unk");
		verbList.put("tear-vb x-nn off-in", "unk");
		verbList.put("tear-vb x-nn open-in", "unk");
		verbList.put("tear-vb x-nn up-in", "unk");
		verbList.put("tease-vb x-nn apart-in", "unk");
		verbList.put("tease-vb x-nn open-in", "unk");
		verbList.put("tease-vb x-nn out-in", "unk");
		verbList.put("tee-vb x-nn off-in", "unk");
		verbList.put("tense-vb x-nn up-in", "unk");
		verbList.put("thin-vb x-nn out-in", "unk");
		verbList.put("think-vb x-nn through-in", "unk");
		verbList.put("think-vb x-nn up-in", "unk");
		verbList.put("throttle-vb x-nn back-in", "unk");
		verbList.put("throw-vb x-nn away-in", "unk");
		verbList.put("throw-vb x-nn in-in", "unk");
		verbList.put("throw-vb x-nn open-in", "unk");
		verbList.put("throw-vb x-nn out-in", "unk");
		verbList.put("throw-vb x-nn over-in", "unk");
		verbList.put("throw-vb x-nn up-in", "unk");
		verbList.put("thrust-vb x-nn out-in", "unk");
		verbList.put("tick-vb x-nn off-in", "unk");
		verbList.put("tidy-vb x-nn up-in", "unk");
		verbList.put("tie-vb x-nn in-in", "unk");
		verbList.put("tie-vb x-nn on-in", "unk");
		verbList.put("tie-vb x-nn up-in", "unk");
		verbList.put("tighten-vb x-nn up-in", "unk");
		verbList.put("tip-vb x-nn off-in", "unk");
		verbList.put("tip-vb x-nn over-in", "unk");
		verbList.put("tire-vb x-nn out-in", "unk");
		verbList.put("tone-vb x-nn down-in", "unk");
		verbList.put("toss-vb x-nn away-in", "unk");
		verbList.put("total-vb x-nn up-in", "unk");
		verbList.put("touch-vb x-nn off-in", "unk");
		verbList.put("towel-vb x-nn off-in", "unk");
		verbList.put("trace-vb x-nn back-in", "unk");
		verbList.put("trace-vb x-nn down-in", "unk");
		verbList.put("track-vb x-nn down-in", "unk");
		verbList.put("trade-vb x-nn in-in", "unk");
		verbList.put("trim-vb x-nn away-in", "unk");
		verbList.put("trim-vb x-nn down-in", "unk");
		verbList.put("trim-vb x-nn off-in", "unk");
		verbList.put("truss-vb x-nn up-in", "unk");
		verbList.put("try-vb x-nn out-in", "unk");
		verbList.put("tuck-vb x-nn in-in", "unk");
		verbList.put("tune-vb x-nn in-in", "unk");
		verbList.put("tune-vb x-nn out-in", "unk");
		verbList.put("tune-vb x-nn up-in", "unk");
		verbList.put("turn-vb x-nn back-in", "unk");
		verbList.put("turn-vb x-nn down-in", "unk");
		verbList.put("turn-vb x-nn in-in", "unk");
		verbList.put("turn-vb x-nn off-in", "unk");
		verbList.put("turn-vb x-nn on-in", "unk");
		verbList.put("turn-vb x-nn out-in", "unk");
		verbList.put("turn-vb x-nn over-in", "unk");
		verbList.put("turn-vb x-nn up-in", "unk");
		verbList.put("type-vb x-nn in-in", "unk");
		verbList.put("type-vb x-nn out-in", "unk");
		verbList.put("type-vb x-nn up-in", "unk");
		verbList.put("use-vb x-nn up-in", "unk");
		verbList.put("usher-vb x-nn in-in", "unk");
		verbList.put("vomit-vb x-nn up-in", "unk");
		verbList.put("wake-vb x-nn x-vb x-nn up-in", "unk");
		verbList.put("wall-vb x-nn in-in", "unk");
		verbList.put("wall-vb x-nn off-in", "unk");
		verbList.put("want-vb x-nn back-in", "unk");
		verbList.put("ward-vb x-nn off-in", "unk");
		verbList.put("warm-vb x-nn up-in", "unk");
		verbList.put("wash-vb x-nn away-in", "unk");
		verbList.put("wash-vb x-nn down-in", "unk");
		verbList.put("wash-vb x-nn out-in", "unk");
		verbList.put("wash-vb x-nn up-in", "unk");
		verbList.put("wear-vb x-nn away-in", "unk");
		verbList.put("wear-vb x-nn out-in", "unk");
		verbList.put("wedge-vb x-nn in-in", "unk");
		verbList.put("weed-vb x-nn out-in", "unk");
		verbList.put("weigh-vb x-nn down-in", "unk");
		verbList.put("weigh-vb x-nn up-in", "unk");
		verbList.put("wheel-vb x-nn in-in", "unk");
		verbList.put("wheel-vb x-nn out-in", "unk");
		verbList.put("whip-vb x-nn in-in", "unk");
		verbList.put("whip-vb x-nn off-in", "unk");
		verbList.put("whip-vb x-nn out-in", "unk");
		verbList.put("whisk-vb x-nn away-in", "unk");
		verbList.put("whistle-vb x-nn up-in", "unk");
		verbList.put("winch-vb x-nn in-in", "unk");
		verbList.put("winch-vb x-nn up-in", "unk");
		verbList.put("wind-vb x-nn down-in", "unk");
		verbList.put("wind-vb x-nn up-in", "unk");
		verbList.put("winnow-vb x-nn out-in", "unk");
		verbList.put("wipe-vb x-nn off-in", "unk");
		verbList.put("wipe-vb x-nn out-in", "unk");
		verbList.put("wipe-vb x-nn up-in", "unk");
		verbList.put("wolf-vb x-nn down-in", "unk");
		verbList.put("work-vb x-nn in-in", "unk");
		verbList.put("work-vb x-nn out-in", "unk");
		verbList.put("wrap-vb x-nn up-in", "unk");
		verbList.put("wrest-vb x-nn away-in", "unk");
		verbList.put("wring-vb x-nn out-in", "unk");
		verbList.put("write-vb x-nn back-in", "unk");
		verbList.put("write-vb x-nn down-in", "unk");
		verbList.put("write-vb x-nn in-in", "unk");
		verbList.put("write-vb x-nn off-in", "unk");
		verbList.put("write-vb x-nn out-in", "unk");
		verbList.put("write-vb x-nn up-in", "unk");
		verbList.put("yield-vb x-nn up-in", "unk");
	}
}
