package linguistic;

import java.util.HashMap;

public class DBLookup {
	
	/** Takes a query string in the form of
	 *    average-vb out-in
	 *    
	 *  
	 * @param queryString
	 * @return definition of the phrase
	 */
	public static String search(String queryString) {
		if (verbList.containsKey(queryString)) {
			return verbList.get(queryString);
		}
		return "no definition found";
	}
	
	/**
	 * This is a placeholder for lookup up a search string in the database.
	 * 
	 * Until our verbs are in the db with definitions, I'm using
	 * this little hashmap.
	 */
	
	private static HashMap<String, String> verbList = new HashMap<String, String>();
	static {
		
		/** 
		 * Case 1: uninterrupted verb-prep 
		 * 		e.g. "back away" but not "back it away"
		 * 
		 **/
		verbList.put("take-VB x-NN in-IN", "absorb, kinda");
		verbList.put("get-VB x-NN of-IN", "what");
		verbList.put("keep-VB tabs-NN on-IN", "track activity");
		verbList.put("act-VB up-IN", "unk");
		verbList.put("add-VB up-IN", "unk");
		verbList.put("air-VB out-IN", "unk");
		verbList.put("amp-VB up-IN", "unk");
		verbList.put("average-VB out-IN", "unk");
		verbList.put("babble-VB on-IN", "unk");
		verbList.put("back-VB away-IN", "unk");
		verbList.put("back-VB down-IN", "unk");
		verbList.put("back-VB off-IN", "unk");
		verbList.put("back-VB out-IN", "unk");
		verbList.put("back-VB up-IN", "unk");
		verbList.put("band-VB together-IN", "unk");
		verbList.put("black-VB out-IN", "unk");
		verbList.put("blank-VB out-IN", "unk");
		verbList.put("blast-VB off-IN", "unk");
		verbList.put("blow-VB up-IN", "unk");
		verbList.put("bog-VB down-IN", "unk");
		verbList.put("boil-VB down-IN", "unk");
		verbList.put("boil-VB over-IN", "unk");
		verbList.put("boil-VB up-IN", "unk");
		verbList.put("boot-VB up-IN", "unk");
		verbList.put("bottom-VB out-IN", "unk");
		verbList.put("bounce-VB back-IN", "unk");
		verbList.put("bow-VB down-IN", "unk");
		verbList.put("bow-VB out-IN", "unk");
		verbList.put("branch-VB off-IN", "unk");
		verbList.put("branch-VB out-IN", "unk");
		verbList.put("break-VB down-IN", "unk");
		verbList.put("break-VB in-IN", "unk");
		verbList.put("break-VB off-IN", "unk");
		verbList.put("break-VB open-IN", "unk");
		verbList.put("break-VB out-IN", "unk");
		verbList.put("break-VB through-IN", "unk");
		verbList.put("break-VB up-IN", "unk");
		verbList.put("bubble-VB over-IN", "unk");
		verbList.put("bubble-VB up-IN", "unk");
		verbList.put("build-VB on-IN", "unk");
		verbList.put("build-VB up-IN", "unk");
		verbList.put("bulk-VB up-IN", "unk");
		verbList.put("bundle-VB up-IN", "unk");
		verbList.put("burn-VB down-IN", "unk");
		verbList.put("burn-VB off-IN", "unk");
		verbList.put("burn-VB out-IN", "unk");
		verbList.put("burn-VB up-IN", "unk");
		verbList.put("burst-VB open-IN", "unk");
		verbList.put("bust-VB open-IN", "unk");
		verbList.put("bust-VB up-IN", "unk");
		verbList.put("butt-VB in-IN", "unk");
		verbList.put("button-VB up-IN", "unk");
		verbList.put("call-VB back-IN", "unk");
		verbList.put("call-VB out-IN", "unk");
		verbList.put("calm-VB down-IN", "unk");
		verbList.put("camp-VB out-IN", "unk");
		verbList.put("cancel-VB out-IN", "unk");
		verbList.put("carry-VB on-IN", "unk");
		verbList.put("cast-VB off-IN", "unk");
		verbList.put("catch-VB up-IN", "unk");
		verbList.put("cave-VB in-IN", "unk");
		verbList.put("chatter-VB on-IN", "unk");
		verbList.put("check-VB in-IN", "unk");
		verbList.put("check-VB out-IN", "unk");
		verbList.put("cheer-VB up-IN", "unk");
		verbList.put("chill-VB out-IN", "unk");
		verbList.put("chime-VB in-IN", "unk");
		verbList.put("choke-VB up-IN", "unk");
		verbList.put("clam-VB up-IN", "unk");
		verbList.put("clamp-VB down-IN", "unk");
		verbList.put("clean-VB up-IN", "unk");
		verbList.put("clear-VB off-IN", "unk");
		verbList.put("clear-VB out-IN", "unk");
		verbList.put("clear-VB up-IN", "unk");
		verbList.put("cling-VB on-IN", "unk");
		verbList.put("clock-VB in-IN", "unk");
		verbList.put("clog-VB up-IN", "unk");
		verbList.put("close-VB down-IN", "unk");
		verbList.put("close-VB in-IN", "unk");
		verbList.put("close-VB off-IN", "unk");
		verbList.put("close-VB out-IN", "unk");
		verbList.put("close-VB up-IN", "unk");
		verbList.put("clown-VB around-IN", "unk");
		verbList.put("coil-VB up-IN", "unk");
		verbList.put("come-VB about-IN", "unk");
		verbList.put("come-VB across-IN", "unk");
		verbList.put("come-VB along-IN", "unk");
		verbList.put("come-VB around-IN", "unk");
		verbList.put("come-VB back-IN", "unk");
		verbList.put("come-VB in-IN", "unk");
		verbList.put("come-VB on-IN", "unk");
		verbList.put("come-VB out-IN", "unk");
		verbList.put("come-VB over-IN", "unk");
		verbList.put("come-VB through-IN", "unk");
		verbList.put("come-VB together-IN", "unk");
		verbList.put("come-VB up-IN", "unk");
		verbList.put("cool-VB down-IN", "unk");
		verbList.put("cool-VB off-IN", "unk");
		verbList.put("cotton-VB on-IN", "unk");
		verbList.put("cough-VB up-IN", "unk");
		verbList.put("crack-VB down-IN", "unk");
		verbList.put("crack-VB open-IN", "unk");
		verbList.put("crack-VB up-IN", "unk");
		verbList.put("crop-VB up-IN", "unk");
		verbList.put("cry-VB out-IN", "unk");
		verbList.put("cut-VB back-IN", "unk");
		verbList.put("cut-VB down-IN", "unk");
		verbList.put("die-VB away-IN", "unk");
		verbList.put("die-VB down-IN", "unk");
		verbList.put("die-VB off-IN", "unk");
		verbList.put("die-VB out-IN", "unk");
		verbList.put("dig-VB in-IN", "unk");
		verbList.put("divide-VB off-IN", "unk");
		verbList.put("divide-VB up-IN", "unk");
		verbList.put("double-VB up-IN", "unk");
		verbList.put("drag-VB on-IN", "unk");
		verbList.put("drag-VB out-IN", "unk");
		verbList.put("draw-VB aside-IN", "unk");
		verbList.put("draw-VB away-IN", "unk");
		verbList.put("draw-VB back-IN", "unk");
		verbList.put("dress-VB up-IN", "unk");
		verbList.put("drift-VB off-IN", "unk");
		verbList.put("drink-VB up-IN", "unk");
		verbList.put("drive-VB around-IN", "unk");
		verbList.put("drive-VB off-IN", "unk");
		verbList.put("drive-VB up-IN", "unk");
		verbList.put("drop-VB by-IN", "unk");
		verbList.put("drop-VB in-IN", "unk");
		verbList.put("drop-VB off-IN", "unk");
		verbList.put("drop-VB out-IN", "unk");
		verbList.put("dry-VB off-IN", "unk");
		verbList.put("dry-VB out-IN", "unk");
		verbList.put("dry-VB up-IN", "unk");
		verbList.put("duck-VB out-IN", "unk");
		verbList.put("ease-VB up-IN", "unk");
		verbList.put("eat-VB in-IN", "unk");
		verbList.put("eat-VB out-IN", "unk");
		verbList.put("even-VB out-IN", "unk");
		verbList.put("fess-VB up-IN", "unk");
		verbList.put("fight-VB back-IN", "unk");
		verbList.put("figure-VB in-IN", "unk");
		verbList.put("fill-VB in-IN", "unk");
		verbList.put("fill-VB out-IN", "unk");
		verbList.put("find-VB out-IN", "unk");
		verbList.put("finish-VB off-IN", "unk");
		verbList.put("finish-VB up-IN", "unk");
		verbList.put("firm-VB up-IN", "unk");
		verbList.put("fit-VB in-IN", "unk");
		verbList.put("flake-VB off-IN", "unk");
		verbList.put("flare-VB up-IN", "unk");
		verbList.put("flatten-VB out-IN", "unk");
		verbList.put("flick-VB off-IN", "unk");
		verbList.put("flick-VB on-IN", "unk");
		verbList.put("flip-VB out-IN", "unk");
		verbList.put("flunk-VB out-IN", "unk");
		verbList.put("fly-VB off-IN", "unk");
		verbList.put("fly-VB on-IN", "unk");
		verbList.put("fly-VB over-IN", "unk");
		verbList.put("follow-VB up-IN", "unk");
		verbList.put("fool-VB around-IN", "unk");
		verbList.put("fork-VB off-IN", "unk");
		verbList.put("freak-VB out-IN", "unk");
		verbList.put("freeze-VB up-IN", "unk");
		verbList.put("freshen-VB up-IN", "unk");
		verbList.put("fry-VB up-IN", "unk");
		verbList.put("fuck-VB around-IN", "unk");
		verbList.put("fuck-VB off-IN", "unk");
		verbList.put("fuck-VB up-IN", "unk");
		verbList.put("fumble-VB around-IN", "unk");
		verbList.put("gas-VB up-IN", "unk");
		verbList.put("gear-VB up-IN", "unk");
		verbList.put("get-VB along-IN", "unk");
		verbList.put("get-VB around-IN", "unk");
		verbList.put("get-VB through-IN", "unk");
		verbList.put("get-VB up-IN", "unk");
		verbList.put("give-VB in-IN", "unk");
		verbList.put("give-VB out-IN", "unk");
		verbList.put("give-VB up-IN", "unk");
		verbList.put("go-VB ahead-IN", "unk");
		verbList.put("go-VB along-VB with-IN", "unk");
		verbList.put("go-VB away-IN", "unk");
		verbList.put("go-VB off-IN", "unk");
		verbList.put("go-VB out-IN", "unk");
		verbList.put("go-VB through-IN", "unk");
		verbList.put("gray-VB out-IN", "unk");
		verbList.put("grey-VB out-IN", "unk");
		verbList.put("ground-VB out-IN", "unk");
		verbList.put("grow-VB over-IN", "unk");
		verbList.put("grow-VB up-IN", "unk");
		verbList.put("hang-VB about-IN", "unk");
		verbList.put("hang-VB around-IN", "unk");
		verbList.put("hang-VB on-IN", "unk");
		verbList.put("hang-VB out-IN", "unk");
		verbList.put("hang-VB up-IN", "unk");
		verbList.put("haul-VB off-IN", "unk");
		verbList.put("head-VB off-IN", "unk");
		verbList.put("head-VB on-IN", "unk");
		verbList.put("head-VB out-IN", "unk");
		verbList.put("help-VB out-IN", "unk");
		verbList.put("hide-VB away-IN", "unk");
		verbList.put("hide-VB out-IN", "unk");
		verbList.put("hold-VB back-IN", "unk");
		verbList.put("hold-VB off-IN", "unk");
		verbList.put("hold-VB on-IN", "unk");
		verbList.put("hold-VB out-IN", "unk");
		verbList.put("hold-VB still-IN", "unk");
		verbList.put("hold-VB up-IN", "unk");
		verbList.put("hole-VB up-IN", "unk");
		verbList.put("home-VB in-IN", "unk");
		verbList.put("hook-VB up-IN", "unk");
		verbList.put("hot-VB up-IN", "unk");
		verbList.put("hunker-VB down-IN", "unk");
		verbList.put("hurry-VB up-IN", "unk");
		verbList.put("ice-VB over-IN", "unk");
		verbList.put("jet-VB off-IN", "unk");
		verbList.put("jump-VB up-IN", "unk");
		verbList.put("keel-VB over-IN", "unk");
		verbList.put("keep-VB up-IN", "unk");
		verbList.put("kick-VB in-IN", "unk");
		verbList.put("kick-VB off-IN", "unk");
		verbList.put("kick-VB up-IN", "unk");
		verbList.put("knot-VB up-IN", "unk");
		verbList.put("knuckle-VB down-IN", "unk");
		verbList.put("knuckle-VB under-IN", "unk");
		verbList.put("lag-VB behind-IN", "unk");
		verbList.put("lash-VB out-IN", "unk");
		verbList.put("lay-VB down-IN", "unk");
		verbList.put("lead-VB on-IN", "unk");
		verbList.put("leave-VB off-IN", "unk");
		verbList.put("let-VB go-IN", "unk");
		verbList.put("let-VB out-IN", "unk");
		verbList.put("let-VB up-IN", "unk");
		verbList.put("level-VB off-IN", "unk");
		verbList.put("level-VB out-IN", "unk");
		verbList.put("lift-VB away-IN", "unk");
		verbList.put("lift-VB off-IN", "unk");
		verbList.put("lift-VB out-IN", "unk");
		verbList.put("lift-VB up-IN", "unk");
		verbList.put("light-VB up-IN", "unk");
		verbList.put("line-VB out-IN", "unk");
		verbList.put("line-VB up-IN", "unk");
		verbList.put("link-VB up-IN", "unk");
		verbList.put("listen-VB in-IN", "unk");
		verbList.put("listen-VB up-IN", "unk");
		verbList.put("lock-VB on-IN", "unk");
		verbList.put("lock-VB up-IN", "unk");
		verbList.put("log-VB in-IN", "unk");
		verbList.put("log-VB off-IN", "unk");
		verbList.put("log-VB on-IN", "unk");
		verbList.put("log-VB out-IN", "unk");
		verbList.put("look-VB around-IN", "unk");
		verbList.put("look-VB on-IN", "unk");
		verbList.put("look-VB up-IN", "unk");
		verbList.put("lose-VB out-IN", "unk");
		verbList.put("louse-VB up-IN", "unk");
		verbList.put("make-VB up-IN", "unk");
		verbList.put("match-VB up-IN", "unk");
		verbList.put("meet-VB up-IN", "unk");
		verbList.put("melt-VB down-IN", "unk");
		verbList.put("mess-VB around-IN", "unk");
		verbList.put("mess-VB up-IN", "unk");
		verbList.put("mount-VB up-IN", "unk");
		verbList.put("move-VB about-IN", "unk");
		verbList.put("move-VB in-IN", "unk");
		verbList.put("move-VB on-IN", "unk");
		verbList.put("move-VB out-IN", "unk");
		verbList.put("move-VB up-IN", "unk");
		verbList.put("muddle-VB along-IN", "unk");
		verbList.put("muddle-VB through-IN", "unk");
		verbList.put("nose-VB around-IN", "unk");
		verbList.put("open-VB up-IN", "unk");
		verbList.put("opt-VB out-IN", "unk");
		verbList.put("pack-VB up-IN", "unk");
		verbList.put("parachute-VB in-IN", "unk");
		verbList.put("patch-VB in-IN", "unk");
		verbList.put("peter-VB out-IN", "unk");
		verbList.put("phase-VB in-IN", "unk");
		verbList.put("phase-VB out-IN", "unk");
		verbList.put("pick-VB up-IN", "unk");
		verbList.put("pig-VB out-IN", "unk");
		verbList.put("pile-VB up-IN", "unk");
		verbList.put("pipe-VB down-IN", "unk");
		verbList.put("pipe-VB up-IN", "unk");
		verbList.put("pluck-VB up-IN", "unk");
		verbList.put("plug-VB in-IN", "unk");
		verbList.put("poke-VB out-IN", "unk");
		verbList.put("poke-VB up-IN", "unk");
		verbList.put("polish-VB up-IN", "unk");
		verbList.put("pop-VB down-IN", "unk");
		verbList.put("pop-VB off-IN", "unk");
		verbList.put("pop-VB out-IN", "unk");
		verbList.put("pop-VB up-IN", "unk");
		verbList.put("pour-VB down-IN", "unk");
		verbList.put("pour-VB in-IN", "unk");
		verbList.put("pour-VB off-IN", "unk");
		verbList.put("pour-VB out-IN", "unk");
		verbList.put("power-VB down-IN", "unk");
		verbList.put("power-VB up-IN", "unk");
		verbList.put("press-VB on-IN", "unk");
		verbList.put("pull-VB apart-IN", "unk");
		verbList.put("pull-VB away-IN", "unk");
		verbList.put("pull-VB back-IN", "unk");
		verbList.put("pull-VB in-IN", "unk");
		verbList.put("pull-VB open-IN", "unk");
		verbList.put("pull-VB out-IN", "unk");
		verbList.put("pull-VB up-IN", "unk");
		verbList.put("pump-VB in-IN", "unk");
		verbList.put("pump-VB out-IN", "unk");
		verbList.put("pump-VB up-IN", "unk");
		verbList.put("push-VB back-IN", "unk");
		verbList.put("push-VB forward-IN", "unk");
		verbList.put("push-VB off-IN", "unk");
		verbList.put("push-VB open-IN", "unk");
		verbList.put("put-VB in-IN", "unk");
		verbList.put("put-VB out-IN", "unk");
		verbList.put("put-VB up-IN", "unk");
		verbList.put("queue-VB up-IN", "unk");
		verbList.put("rabbit-VB on-IN", "unk");
		verbList.put("rack-VB up-IN", "unk");
		verbList.put("ramp-VB up-IN", "unk");
		verbList.put("rave-VB on-IN", "unk");
		verbList.put("reach-VB out-IN", "unk");
		verbList.put("rein-VB in-IN", "unk");
		verbList.put("rest-VB up-IN", "unk");
		verbList.put("rocket-VB up-IN", "unk");
		verbList.put("roll-VB over-IN", "unk");
		verbList.put("romp-VB around-IN", "unk");
		verbList.put("root-VB around-IN", "unk");
		verbList.put("run-VB around-IN", "unk");
		verbList.put("run-VB back-IN", "unk");
		verbList.put("run-VB out-IN", "unk");
		verbList.put("run-VB over-IN", "unk");
		verbList.put("rust-VB away-IN", "unk");
		verbList.put("rust-VB in-IN", "unk");
		verbList.put("rust-VB out-IN", "unk");
		verbList.put("sack-VB out-IN", "unk");
		verbList.put("saddle-VB up-IN", "unk");
		verbList.put("scale-VB up-IN", "unk");
		verbList.put("screw-VB up-IN", "unk");
		verbList.put("seize-VB up-IN", "unk");
		verbList.put("sell-VB out-IN", "unk");
		verbList.put("set-VB off-IN", "unk");
		verbList.put("set-VB out-IN", "unk");
		verbList.put("set-VB up-IN", "unk");
		verbList.put("settle-VB down-IN", "unk");
		verbList.put("settle-VB in-IN", "unk");
		verbList.put("shack-VB up-IN", "unk");
		verbList.put("sharpen-VB up-IN", "unk");
		verbList.put("shell-VB out-IN", "unk");
		verbList.put("shine-VB out-IN", "unk");
		verbList.put("ship-VB out-IN", "unk");
		verbList.put("shop-VB around-IN", "unk");
		verbList.put("short-VB out-IN", "unk");
		verbList.put("shout-VB out-IN", "unk");
		verbList.put("show-VB up-IN", "unk");
		verbList.put("shut-VB down-IN", "unk");
		verbList.put("shut-VB off-IN", "unk");
		verbList.put("shut-VB up-IN", "unk");
		verbList.put("shy-VB away-IN", "unk");
		verbList.put("sign-VB off-IN", "unk");
		verbList.put("sign-VB on-IN", "unk");
		verbList.put("sign-VB up-IN", "unk");
		verbList.put("silt-VB up-IN", "unk");
		verbList.put("simmer-VB down-IN", "unk");
		verbList.put("sink-VB in-IN", "unk");
		verbList.put("sit-VB down-IN", "unk");
		verbList.put("sit-VB up-IN", "unk");
		verbList.put("skip-VB out-IN", "unk");
		verbList.put("slack-VB off-IN", "unk");
		verbList.put("slacken-VB off-IN", "unk");
		verbList.put("sleep-VB in-IN", "unk");
		verbList.put("slim-VB down-IN", "unk");
		verbList.put("slough-VB off-IN", "unk");
		verbList.put("slow-VB down-IN", "unk");
		verbList.put("slow-VB up-IN", "unk");
		verbList.put("smash-VB up-IN", "unk");
		verbList.put("smooth-VB out-IN", "unk");
		verbList.put("snap-VB in-IN", "unk");
		verbList.put("snap-VB off-IN", "unk");
		verbList.put("snuggle-VB down-IN", "unk");
		verbList.put("snuggle-VB up-IN", "unk");
		verbList.put("soak-VB in-IN", "unk");
		verbList.put("soap-VB up-IN", "unk");
		verbList.put("sober-VB up-IN", "unk");
		verbList.put("soften-VB up-IN", "unk");
		verbList.put("sound-VB off-IN", "unk");
		verbList.put("speed-VB up-IN", "unk");
		verbList.put("spill-VB out-IN", "unk");
		verbList.put("spill-VB over-IN", "unk");
		verbList.put("spin-VB around-IN", "unk");
		verbList.put("spin-VB out-IN", "unk");
		verbList.put("split-VB off-IN", "unk");
		verbList.put("split-VB up-IN", "unk");
		verbList.put("sprawl-VB out-IN", "unk");
		verbList.put("spread-VB out-IN", "unk");
		verbList.put("spring-VB up-IN", "unk");
		verbList.put("spurt-VB out-IN", "unk");
		verbList.put("squeeze-VB in-IN", "unk");
		verbList.put("squeeze-VB out-IN", "unk");
		verbList.put("stack-VB up-IN", "unk");
		verbList.put("stand-VB in-IN", "unk");
		verbList.put("stand-VB out-IN", "unk");
		verbList.put("stand-VB up-IN", "unk");
		verbList.put("start-VB off-IN", "unk");
		verbList.put("start-VB out-IN", "unk");
		verbList.put("start-VB over-IN", "unk");
		verbList.put("start-VB up-IN", "unk");
		verbList.put("stay-VB over-IN", "unk");
		verbList.put("step-VB out-IN", "unk");
		verbList.put("step-VB up-IN", "unk");
		verbList.put("stick-VB around-IN", "unk");
		verbList.put("stick-VB out-IN", "unk");
		verbList.put("stick-VB up-IN", "unk");
		verbList.put("stiffen-VB up-IN", "unk");
		verbList.put("stock-VB up-IN", "unk");
		verbList.put("stop-VB by-IN", "unk");
		verbList.put("stop-VB in-IN", "unk");
		verbList.put("stop-VB off-IN", "unk");
		verbList.put("stop-VB over-IN", "unk");
		verbList.put("straighten-VB out-IN", "unk");
		verbList.put("straighten-VB up-IN", "unk");
		verbList.put("stretch-VB out-IN", "unk");
		verbList.put("stretch-VB over-IN", "unk");
		verbList.put("strike-VB off-IN", "unk");
		verbList.put("strike-VB out-IN", "unk");
		verbList.put("stroll-VB along-IN", "unk");
		verbList.put("sum-VB up-IN", "unk");
		verbList.put("sweep-VB up-IN", "unk");
		verbList.put("swell-VB up-IN", "unk");
		verbList.put("switch-VB off-IN", "unk");
		verbList.put("switch-VB on-IN", "unk");
		verbList.put("tail-VB off-IN", "unk");
		verbList.put("take-VB off-IN", "unk");
		verbList.put("take-VB over-IN", "unk");
		verbList.put("tank-VB up-IN", "unk");
		verbList.put("taper-VB off-IN", "unk");
		verbList.put("team-VB up-IN", "unk");
		verbList.put("tear-VB off-IN", "unk");
		verbList.put("tear-VB up-IN", "unk");
		verbList.put("tee-VB off-IN", "unk");
		verbList.put("tense-VB up-IN", "unk");
		verbList.put("thin-VB out-IN", "unk");
		verbList.put("throw-VB in-IN", "unk");
		verbList.put("throw-VB up-IN", "unk");
		verbList.put("tidy-VB up-IN", "unk");
		verbList.put("tie-VB in-IN", "unk");
		verbList.put("tighten-VB up-IN", "unk");
		verbList.put("tip-VB over-IN", "unk");
		verbList.put("tire-VB out-IN", "unk");
		verbList.put("touch-VB down-IN", "unk");
		verbList.put("towel-VB off-IN", "unk");
		verbList.put("trace-VB back-IN", "unk");
		verbList.put("trail-VB off-IN", "unk");
		verbList.put("tuck-VB in-IN", "unk");
		verbList.put("tune-VB in-IN", "unk");
		verbList.put("tune-VB out-IN", "unk");
		verbList.put("tune-VB up-IN", "unk");
		verbList.put("turn-VB in-IN", "unk");
		verbList.put("turn-VB off-IN", "unk");
		verbList.put("turn-VB on-IN", "unk");
		verbList.put("turn-VB out-IN", "unk");
		verbList.put("turn-VB over-IN", "unk");
		verbList.put("turn-VB up-IN", "unk");
		verbList.put("usher-VB in-IN", "unk");
		verbList.put("wake-VB up-IN", "unk");
		verbList.put("walk-VB over-IN", "unk");
		verbList.put("wander-VB off-IN", "unk");
		verbList.put("wander-VB up-IN", "unk");
		verbList.put("want-VB in-IN", "unk");
		verbList.put("want-VB out-IN", "unk");
		verbList.put("warm-VB up-IN", "unk");
		verbList.put("wash-VB away-IN", "unk");
		verbList.put("wash-VB down-IN", "unk");
		verbList.put("wash-VB out-IN", "unk");
		verbList.put("wash-VB up-IN", "unk");
		verbList.put("watch-VB out-IN", "unk");
		verbList.put("wear-VB away-IN", "unk");
		verbList.put("wear-VB off-IN", "unk");
		verbList.put("wear-VB on-IN", "unk");
		verbList.put("wear-VB out-IN", "unk");
		verbList.put("wear-VB thin-IN", "unk");
		verbList.put("well-VB up-IN", "unk");
		verbList.put("wheel-VB in-IN", "unk");
		verbList.put("wheel-VB out-IN", "unk");
		verbList.put("wind-VB down-IN", "unk");
		verbList.put("wind-VB up-IN", "unk");
		verbList.put("wipe-VB off-IN", "unk");
		verbList.put("wipe-VB out-IN", "unk");
		verbList.put("wipe-VB up-IN", "unk");
		verbList.put("work-VB out-IN", "unk");
		verbList.put("wrap-VB up-IN", "unk");
		verbList.put("write-VB back-IN", "unk");
		verbList.put("zone-VB out-IN", "unk");

		/** 
		 * Case 2: interrupted verb-prep 
		 * 		e.g. break it open
		 * 
		 * Case 3: uninterrupted verb-prep (same as case 1)
		 * 		e.g. break open the safe 
		 **/
		verbList.put("act-VB x-NN out-IN", "unk");
		verbList.put("add-VB x-NN in-IN", "unk");
		verbList.put("add-VB x-NN on-IN", "unk");
		verbList.put("add-VB x-NN up-IN", "unk");
		verbList.put("air-VB x-NN out-IN", "unk");
		verbList.put("amp-VB x-NN up-IN", "unk");
		verbList.put("average-VB x-NN out-IN", "unk");
		verbList.put("back-VB x-NN up-IN", "unk");
		verbList.put("bail-VB x-NN out-IN", "unk");
		verbList.put("balance-VB x-NN out-IN", "unk");
		verbList.put("ball-VB x-NN up-IN", "unk");
		verbList.put("band-VB x-NN together-IN", "unk");
		verbList.put("bandage-VB x-NN up-IN", "unk");
		verbList.put("bang-VB x-NN up-IN", "unk");
		verbList.put("bat-VB x-NN away-IN", "unk");
		verbList.put("bawl-VB x-NN out-IN", "unk");
		verbList.put("beam-VB x-NN out-IN", "unk");
		verbList.put("bear-VB x-NN out-IN", "unk");
		verbList.put("beat-VB x-NN up-IN", "unk");
		verbList.put("bed-VB x-NN down-IN", "unk");
		verbList.put("belt-VB x-NN out-IN", "unk");
		verbList.put("bite-VB x-NN out-IN", "unk");
		verbList.put("black-VB x-NN out-IN", "unk");
		verbList.put("blank-VB x-NN out-IN", "unk");
		verbList.put("blast-VB x-NN away-IN", "unk");
		verbList.put("blast-VB x-NN open-IN", "unk");
		verbList.put("blast-VB x-NN out-IN", "unk");
		verbList.put("bleep-VB x-NN out-IN", "unk");
		verbList.put("block-VB x-NN off-IN", "unk");
		verbList.put("block-VB x-NN out-IN", "unk");
		verbList.put("blot-VB x-NN out-IN", "unk");
		verbList.put("blow-VB x-NN away-IN", "unk");
		verbList.put("blow-VB x-NN down-IN", "unk");
		verbList.put("blow-VB x-NN off-IN", "unk");
		verbList.put("blow-VB x-NN out-IN", "unk");
		verbList.put("blow-VB x-NN up-IN", "unk");
		verbList.put("blur-VB x-NN out-IN", "unk");
		verbList.put("board-VB x-NN up-IN", "unk");
		verbList.put("boil-VB x-NN down-IN", "unk");
		verbList.put("bomb-VB x-NN out-IN", "unk");
		verbList.put("book-VB x-NN up-IN", "unk");
		verbList.put("boot-VB x-NN out-IN", "unk");
		verbList.put("boot-VB x-NN up-IN", "unk");
		verbList.put("bottle-VB x-NN in-IN", "unk");
		verbList.put("bottle-VB x-NN up-IN", "unk");
		verbList.put("bounce-VB x-NN back-IN", "unk");
		verbList.put("bowl-VB x-NN over-IN", "unk");
		verbList.put("box-VB x-NN in-IN", "unk");
		verbList.put("box-VB x-NN up-IN", "unk");
		verbList.put("break-VB x-NN down-IN", "unk");
		verbList.put("break-VB x-NN in-IN", "unk");
		verbList.put("break-VB x-NN off-IN", "unk");
		verbList.put("break-VB x-NN open-IN", "unk");
		verbList.put("break-VB x-NN out-IN", "unk");
		verbList.put("break-VB x-NN up-IN", "unk");
		verbList.put("brick-VB x-NN up-IN", "unk");
		verbList.put("bring-VB x-NN about-IN", "unk");
		verbList.put("bring-VB x-NN along-IN", "unk");
		verbList.put("bring-VB x-NN down-IN", "unk");
		verbList.put("bring-VB x-NN forth-IN", "unk");
		verbList.put("bring-VB x-NN forward-IN", "unk");
		verbList.put("bring-VB x-NN home-IN", "unk");
		verbList.put("bring-VB x-NN in-IN", "unk");
		verbList.put("bring-VB x-NN off-IN", "unk");
		verbList.put("bring-VB x-NN over-IN", "unk");
		verbList.put("bring-VB x-NN together-IN", "unk");
		verbList.put("bring-VB x-NN up-IN", "unk");
		verbList.put("brush-VB x-NN aside-IN", "unk");
		verbList.put("brush-VB x-NN away-IN", "unk");
		verbList.put("brush-VB x-NN off-IN", "unk");
		verbList.put("buff-VB x-NN up-IN", "unk");
		verbList.put("build-VB x-NN in-IN", "unk");
		verbList.put("build-VB x-NN up-IN", "unk");
		verbList.put("bump-VB x-NN off-IN", "unk");
		verbList.put("bundle-VB x-NN up-IN", "unk");
		verbList.put("buoy-VB x-NN up-IN", "unk");
		verbList.put("burn-VB x-NN down-IN", "unk");
		verbList.put("burn-VB x-NN off-IN", "unk");
		verbList.put("burn-VB x-NN out-IN", "unk");
		verbList.put("burn-VB x-NN up-IN", "unk");
		verbList.put("burst-VB x-NN open-IN", "unk");
		verbList.put("bus-VB x-NN in-IN", "unk");
		verbList.put("bust-VB x-NN open-IN", "unk");
		verbList.put("bust-VB x-NN up-IN", "unk");
		verbList.put("button-VB x-NN down-IN", "unk");
		verbList.put("button-VB x-NN up-IN", "unk");
		verbList.put("buy-VB x-NN out-IN", "unk");
		verbList.put("buy-VB x-NN up-IN", "unk");
		verbList.put("call-VB x-NN back-IN", "unk");
		verbList.put("call-VB x-NN off-IN", "unk");
		verbList.put("call-VB x-NN out-IN", "unk");
		verbList.put("call-VB x-NN up-IN", "unk");
		verbList.put("calm-VB x-NN down-IN", "unk");
		verbList.put("cancel-VB x-NN out-IN", "unk");
		verbList.put("carry-VB x-NN away-IN", "unk");
		verbList.put("carry-VB x-NN in-IN", "unk");
		verbList.put("carry-VB x-NN on-IN", "unk");
		verbList.put("carry-VB x-NN out-IN", "unk");
		verbList.put("cart-VB x-NN away-IN", "unk");
		verbList.put("carve-VB x-NN out-IN", "unk");
		verbList.put("carve-VB x-NN up-IN", "unk");
		verbList.put("cash-VB x-NN in-IN", "unk");
		verbList.put("cast-VB x-NN down-IN", "unk");
		verbList.put("cast-VB x-NN off-IN", "unk");
		verbList.put("cast-VB x-NN out-IN", "unk");
		verbList.put("cave-VB x-NN in-IN", "unk");
		verbList.put("chalk-VB x-NN up-IN", "unk");
		verbList.put("charge-VB x-NN up-IN", "unk");
		verbList.put("chase-VB x-NN away-IN", "unk");
		verbList.put("chase-VB x-NN down-IN", "unk");
		verbList.put("chase-VB x-NN up-IN", "unk");
		verbList.put("chat-VB x-NN up-IN", "unk");
		verbList.put("check-VB x-NN in-IN", "unk");
		verbList.put("check-VB x-NN out-IN", "unk");
		verbList.put("cheer-VB x-NN on-IN", "unk");
		verbList.put("cheer-VB x-NN up-IN", "unk");
		verbList.put("chew-VB x-NN off-IN", "unk");
		verbList.put("chew-VB x-NN out-IN", "unk");
		verbList.put("chip-VB x-NN in-IN", "unk");
		verbList.put("choke-VB x-NN off-IN", "unk");
		verbList.put("choke-VB x-NN up-IN", "unk");
		verbList.put("chop-VB x-NN down-IN", "unk");
		verbList.put("chop-VB x-NN off-IN", "unk");
		verbList.put("chop-VB x-NN up-IN", "unk");
		verbList.put("churn-VB x-NN out-IN", "unk");
		verbList.put("clean-VB x-NN out-IN", "unk");
		verbList.put("clean-VB x-NN up-IN", "unk");
		verbList.put("clear-VB x-NN away-IN", "unk");
		verbList.put("clear-VB x-NN off-IN", "unk");
		verbList.put("clear-VB x-NN out-IN", "unk");
		verbList.put("clear-VB x-NN up-IN", "unk");
		verbList.put("clog-VB x-NN up-IN", "unk");
		verbList.put("close-VB x-NN down-IN", "unk");
		verbList.put("close-VB x-NN in-IN", "unk");
		verbList.put("close-VB x-NN off-IN", "unk");
		verbList.put("close-VB x-NN out-IN", "unk");
		verbList.put("close-VB x-NN up-IN", "unk");
		verbList.put("clutter-VB x-NN up-IN", "unk");
		verbList.put("code-VB x-NN up-IN", "unk");
		verbList.put("coil-VB x-NN up-IN", "unk");
		verbList.put("comb-VB x-NN out-IN", "unk");
		verbList.put("conjure-VB x-NN up-IN", "unk");
		verbList.put("contract-VB x-NN out-IN", "unk");
		verbList.put("cook-VB x-NN up-IN", "unk");
		verbList.put("cool-VB x-NN down-IN", "unk");
		verbList.put("cool-VB x-NN off-IN", "unk");
		verbList.put("coop-VB x-NN up-IN", "unk");
		verbList.put("copy-VB x-NN down-IN", "unk");
		verbList.put("copy-VB x-NN out-IN", "unk");
		verbList.put("cough-VB x-NN up-IN", "unk");
		verbList.put("count-VB x-NN out-IN", "unk");
		verbList.put("cover-VB x-NN up-IN", "unk");
		verbList.put("crack-VB x-NN open-IN", "unk");
		verbList.put("crack-VB x-NN up-IN", "unk");
		verbList.put("crank-VB x-NN out-IN", "unk");
		verbList.put("crank-VB x-NN up-IN", "unk");
		verbList.put("credit-VB x-NN back-IN", "unk");
		verbList.put("crisp-VB x-NN up-IN", "unk");
		verbList.put("cross-VB x-NN off-IN", "unk");
		verbList.put("cross-VB x-NN out-IN", "unk");
		verbList.put("crowd-VB x-NN out-IN", "unk");
		verbList.put("curtain-VB x-NN off-IN", "unk");
		verbList.put("cut-VB x-NN apart-IN", "unk");
		verbList.put("cut-VB x-NN back-IN", "unk");
		verbList.put("cut-VB x-NN down-IN", "unk");
		verbList.put("cut-VB x-NN in-IN", "unk");
		verbList.put("cut-VB x-NN off-IN", "unk");
		verbList.put("cut-VB x-NN out-IN", "unk");
		verbList.put("cut-VB x-NN short-IN", "unk");
		verbList.put("cut-VB x-NN up-IN", "unk");
		verbList.put("dam-VB x-NN up-IN", "unk");
		verbList.put("damp-VB x-NN down-IN", "unk");
		verbList.put("damp-VB x-NN out-IN", "unk");
		verbList.put("deck-VB x-NN out-IN", "unk");
		verbList.put("define-VB x-NN away-IN", "unk");
		verbList.put("dial-VB x-NN in-IN", "unk");
		verbList.put("dig-VB x-NN out-IN", "unk");
		verbList.put("dig-VB x-NN up-IN", "unk");
		verbList.put("dish-VB x-NN out-IN", "unk");
		verbList.put("divide-VB x-NN off-IN", "unk");
		verbList.put("divide-VB x-NN up-IN", "unk");
		verbList.put("do-VB x-NN up-IN", "unk");
		verbList.put("dole-VB x-NN out-IN", "unk");
		verbList.put("doll-VB x-NN up-IN", "unk");
		verbList.put("double-VB x-NN up-IN", "unk");
		verbList.put("draft-VB x-NN in-IN", "unk");
		verbList.put("drag-VB x-NN in-IN", "unk");
		verbList.put("drag-VB x-NN on-IN", "unk");
		verbList.put("drag-VB x-NN out-IN", "unk");
		verbList.put("draw-VB x-NN aside-IN", "unk");
		verbList.put("draw-VB x-NN away-IN", "unk");
		verbList.put("draw-VB x-NN back-IN", "unk");
		verbList.put("draw-VB x-NN forth-IN", "unk");
		verbList.put("draw-VB x-NN up-IN", "unk");
		verbList.put("dream-VB x-NN up-IN", "unk");
		verbList.put("dredge-VB x-NN up-IN", "unk");
		verbList.put("dress-VB x-NN up-IN", "unk");
		verbList.put("drink-VB x-NN down-IN", "unk");
		verbList.put("drink-VB x-NN up-IN", "unk");
		verbList.put("drive-VB x-NN around-IN", "unk");
		verbList.put("drive-VB x-NN away-IN", "unk");
		verbList.put("drive-VB x-NN down-IN", "unk");
		verbList.put("drive-VB x-NN home-IN", "unk");
		verbList.put("drive-VB x-NN in-IN", "unk");
		verbList.put("drive-VB x-NN off-IN", "unk");
		verbList.put("drive-VB x-NN out-IN", "unk");
		verbList.put("drive-VB x-NN up-IN", "unk");
		verbList.put("drop-VB x-NN in-IN", "unk");
		verbList.put("drop-VB x-NN off-IN", "unk");
		verbList.put("drop-VB x-NN out-IN", "unk");
		verbList.put("drown-VB x-NN out-IN", "unk");
		verbList.put("dry-VB x-NN off-IN", "unk");
		verbList.put("dry-VB x-NN out-IN", "unk");
		verbList.put("dry-VB x-NN up-IN", "unk");
		verbList.put("dump-VB x-NN out-IN", "unk");
		verbList.put("ease-VB x-NN out-IN", "unk");
		verbList.put("eat-VB x-NN up-IN", "unk");
		verbList.put("eke-VB x-NN out-IN", "unk");
		verbList.put("end-VB x-NN up-IN", "unk");
		verbList.put("enter-VB x-NN in-IN", "unk");
		verbList.put("etch-VB x-NN away-IN", "unk");
		verbList.put("even-VB x-NN out-IN", "unk");
		verbList.put("factor-VB x-NN in-IN", "unk");
		verbList.put("fake-VB x-NN out-IN", "unk");
		verbList.put("feed-VB x-NN in-IN", "unk");
		verbList.put("fence-VB x-NN in-IN", "unk");
		verbList.put("fend-VB x-NN off-IN", "unk");
		verbList.put("ferret-VB x-NN out-IN", "unk");
		verbList.put("ferry-VB x-NN in-IN", "unk");
		verbList.put("figure-VB x-NN in-IN", "unk");
		verbList.put("figure-VB x-NN out-IN", "unk");
		verbList.put("fill-VB x-NN in-IN", "unk");
		verbList.put("fill-VB x-NN out-IN", "unk");
		verbList.put("filter-VB x-NN out-IN", "unk");
		verbList.put("find-VB x-NN out-IN", "unk");
		verbList.put("finish-VB x-NN off-IN", "unk");
		verbList.put("finish-IN", "unk");				//???
		verbList.put("fire-IN", "unk");					//???
		verbList.put("firm-VB x-NN up-IN", "unk");
		verbList.put("fish-VB x-NN out-IN", "unk");
		verbList.put("fit-VB x-NN in-IN", "unk");
		verbList.put("fix-VB x-NN up-IN", "unk");
		verbList.put("flag-VB x-NN down-IN", "unk");
		verbList.put("flake-VB x-NN off-IN", "unk");
		verbList.put("flatten-VB x-NN out-IN", "unk");
		verbList.put("flesh-VB x-NN out-IN", "unk");
		verbList.put("flick-VB x-NN off-IN", "unk");
		verbList.put("flick-VB x-NN on-IN", "unk");
		verbList.put("fling-VB x-NN back-IN", "unk");
		verbList.put("fling-VB x-NN off-IN", "unk");
		verbList.put("fling-VB x-NN open-IN", "unk");
		verbList.put("flush-VB x-NN out-IN", "unk");
		verbList.put("fly-VB x-NN in-IN", "unk");
		verbList.put("fog-VB x-NN up-IN", "unk");
		verbList.put("follow-VB x-NN around-IN", "unk");
		verbList.put("follow-VB x-NN up-IN", "unk");
		verbList.put("fork-VB x-NN out-IN", "unk");
		verbList.put("fork-VB x-NN over-IN", "unk");
		verbList.put("frame-VB x-NN in-IN", "unk");
		verbList.put("freak-VB x-NN out-IN", "unk");
		verbList.put("free-VB x-NN up-IN", "unk");
		verbList.put("frighten-VB x-NN off-IN", "unk");
		verbList.put("fritter-VB x-NN away-IN", "unk");
		verbList.put("fuck-VB x-NN up-IN", "unk");
		verbList.put("gamble-VB x-NN away-IN", "unk");
		verbList.put("gas-VB x-NN up-IN", "unk");
		verbList.put("gather-VB x-NN up-IN", "unk");
		verbList.put("gear-VB x-NN up-IN", "unk");
		verbList.put("get-VB x-NN back-IN", "unk");
		verbList.put("get-VB x-NN down-IN", "unk");
		verbList.put("get-VB x-NN in-IN", "unk");
		verbList.put("get-VB x-NN off-IN", "unk");
		verbList.put("get-VB x-NN out-IN", "unk");
		verbList.put("give-VB x-NN back-IN", "unk");
		verbList.put("give-VB x-NN off-IN", "unk");
		verbList.put("give-VB x-NN out-IN", "unk");
		verbList.put("give-VB x-NN up-IN", "unk");
		verbList.put("gnaw-VB x-NN away-IN", "unk");
		verbList.put("gobble-VB x-NN up-IN", "unk");
		verbList.put("gouge-VB x-NN away-IN", "unk");
		verbList.put("gouge-VB x-NN out-IN", "unk");
		verbList.put("grandfather-VB x-NN in-IN", "unk");
		verbList.put("gray-VB x-NN out-IN", "unk");
		verbList.put("grease-VB x-NN up-IN", "unk");
		verbList.put("grey-VB x-NN out-IN", "unk");
		verbList.put("grind-VB x-NN out-IN", "unk");
		verbList.put("gulp-VB x-NN down-IN", "unk");
		verbList.put("gun-VB x-NN down-IN", "unk");
		verbList.put("gut-VB x-NN out-IN", "unk");
		verbList.put("hack-VB x-NN up-IN", "unk");
		verbList.put("hammer-VB x-NN out-IN", "unk");
		verbList.put("hand-VB x-NN in-IN", "unk");
		verbList.put("hand-VB x-NN off-IN", "unk");
		verbList.put("hand-VB x-NN out-IN", "unk");
		verbList.put("hand-VB x-NN over-IN", "unk");
		verbList.put("hang-VB x-NN out-IN", "unk");
		verbList.put("hang-VB x-NN up-IN", "unk");
		verbList.put("harness-VB x-NN up-IN", "unk");
		verbList.put("hash-VB x-NN out-IN", "unk");
		verbList.put("haul-VB x-NN away-IN", "unk");
		verbList.put("haul-VB x-NN in-IN", "unk");
		verbList.put("haul-VB x-NN off-IN", "unk");
		verbList.put("haul-VB x-NN out-IN", "unk");
		verbList.put("haul-VB x-NN up-IN", "unk");
		verbList.put("have-VB x-NN back-IN", "unk");
		verbList.put("have-VB x-NN off-IN", "unk");
		verbList.put("head-VB x-NN off-IN", "unk");
		verbList.put("head-VB x-NN up-IN", "unk");
		verbList.put("heat-VB x-NN up-IN", "unk");
		verbList.put("heat-VB x-NN up-IN", "unk");
		verbList.put("help-VB x-NN out-IN", "unk");
		verbList.put("hem-VB x-NN in-IN", "unk");
		verbList.put("hem-VB x-NN out-IN", "unk");
		verbList.put("hew-VB x-NN out-IN", "unk");
		verbList.put("hide-VB x-NN away-IN", "unk");
		verbList.put("hike-VB x-NN up-IN", "unk");
		verbList.put("hitch-VB x-NN up-IN", "unk");
		verbList.put("hoist-VB x-NN up-IN", "unk");
		verbList.put("hold-VB x-NN back-IN", "unk");
		verbList.put("hold-VB x-NN down-IN", "unk");
		verbList.put("hold-VB x-NN in-IN", "unk");
		verbList.put("hold-VB x-NN off-IN", "unk");
		verbList.put("hold-VB x-NN out-IN", "unk");
		verbList.put("hold-VB x-NN up-IN", "unk");
		verbList.put("hole-VB x-NN up-IN", "unk");
		verbList.put("hollow-VB x-NN out-IN", "unk");
		verbList.put("hook-VB x-NN up-IN", "unk");
		verbList.put("hose-VB x-NN down-IN", "unk");
		verbList.put("hunch-VB x-NN up-IN", "unk");
		verbList.put("hunt-VB x-NN down-IN", "unk");
		verbList.put("hunt-VB x-NN out-IN", "unk");
		verbList.put("hunt-VB x-NN up-IN", "unk");
		verbList.put("hurry-VB x-NN up-IN", "unk");
		verbList.put("invite-VB x-NN in-IN", "unk");
		verbList.put("invite-VB x-NN out-IN", "unk");
		verbList.put("iron-VB x-NN out-IN", "unk");
		verbList.put("isolate-VB x-NN out-IN", "unk");
		verbList.put("jack-VB x-NN up-IN", "unk");
		verbList.put("jam-VB x-NN up-IN", "unk");
		verbList.put("jot-VB x-NN down-IN", "unk");
		verbList.put("juggle-VB x-NN around-IN", "unk");
		verbList.put("keep-VB x-NN out-IN", "unk");
		verbList.put("keep-VB x-NN up-IN", "unk");
		verbList.put("key-VB x-NN in-IN", "unk");
		verbList.put("kick-VB x-NN in-IN", "unk");
		verbList.put("kick-VB x-NN off-IN", "unk");
		verbList.put("kick-VB x-NN out-IN", "unk");
		verbList.put("kick-VB x-NN up-IN", "unk");
		verbList.put("kill-VB x-NN off-IN", "unk");
		verbList.put("kit-VB x-NN out-IN", "unk");
		verbList.put("knock-VB x-NN off-IN", "unk");
		verbList.put("knock-VB x-NN out-IN", "unk");
		verbList.put("knock-VB x-NN over-IN", "unk");
		verbList.put("knock-VB x-NN up-IN", "unk");
		verbList.put("knot-VB x-NN up-IN", "unk");
		verbList.put("lace-VB x-NN up-IN", "unk");
		verbList.put("last-VB x-NN out-IN", "unk");
		verbList.put("laugh-VB x-NN off-IN", "unk");
		verbList.put("lay-VB x-NN off-IN", "unk");
		verbList.put("lay-VB x-NN on-IN", "unk");
		verbList.put("lay-VB x-NN out-IN", "unk");
		verbList.put("lay-VB x-NN up-IN", "unk");
		verbList.put("lead-VB x-NN on-IN", "unk");
		verbList.put("leave-VB x-NN behind-IN", "unk");
		verbList.put("leave-VB x-NN home-IN", "unk");
		verbList.put("leave-VB x-NN in-IN", "unk");
		verbList.put("leave-VB x-NN off-IN", "unk");
		verbList.put("leave-VB x-NN open-IN", "unk");
		verbList.put("leave-VB x-NN out-IN", "unk");
		verbList.put("leave-VB x-NN over-IN", "unk");
		verbList.put("let-VB x-NN down-IN", "unk");
		verbList.put("let-VB x-NN in-IN", "unk");
		verbList.put("let-VB x-NN off-IN", "unk");
		verbList.put("let-VB x-NN out-IN", "unk");
		verbList.put("level-VB x-NN off-IN", "unk");
		verbList.put("level-VB x-NN out-IN", "unk");
		verbList.put("lift-VB x-NN away-IN", "unk");
		verbList.put("lift-VB x-NN off-IN", "unk");
		verbList.put("lift-VB x-NN out-IN", "unk");
		verbList.put("lift-VB x-NN up-IN", "unk");
		verbList.put("light-VB x-NN up-IN", "unk");
		verbList.put("like-VB x-NN back-IN", "unk");
		verbList.put("limit-VB x-NN down-IN", "unk");
		verbList.put("line-VB x-NN out-IN", "unk");
		verbList.put("line-VB x-NN up-IN", "unk");
		verbList.put("link-VB x-NN up-IN", "unk");
		verbList.put("live-VB x-NN down-IN", "unk");
		verbList.put("live-VB x-NN out-IN", "unk");
		verbList.put("live-VB x-NN up-IN", "unk");
		verbList.put("load-VB x-NN up-IN", "unk");
		verbList.put("loan-VB x-NN out-IN", "unk");
		verbList.put("lock-VB x-NN away-IN", "unk");
		verbList.put("lock-VB x-NN down-IN", "unk");
		verbList.put("lock-VB x-NN in-IN", "unk");
		verbList.put("lock-VB x-NN on-IN", "unk");
		verbList.put("lock-VB x-NN out-IN", "unk");
		verbList.put("lock-VB x-NN up-IN", "unk");
		verbList.put("log-VB x-NN in-IN", "unk");
		verbList.put("log-VB x-NN off-IN", "unk");
		verbList.put("log-VB x-NN on-IN", "unk");
		verbList.put("log-VB x-NN out-IN", "unk");
		verbList.put("look-VB x-NN over-IN", "unk");
		verbList.put("look-VB x-NN up-IN", "unk");
		verbList.put("lop-VB x-NN off-IN", "unk");
		verbList.put("louse-VB x-NN up-IN", "unk");
		verbList.put("lump-VB x-NN in-IN", "unk");
		verbList.put("mail-VB x-NN back-IN", "unk");
		verbList.put("mail-VB x-NN in-IN", "unk");
		verbList.put("mail-VB x-NN out-IN", "unk");
		verbList.put("make-VB x-NN out-IN", "unk");
		verbList.put("make-VB x-NN up-IN", "unk");
		verbList.put("map-VB x-NN out-IN", "unk");
		verbList.put("march-VB x-NN off-IN", "unk");
		verbList.put("mark-VB x-NN down-IN", "unk");
		verbList.put("mark-VB x-NN off-IN", "unk");
		verbList.put("mark-VB x-NN out-IN", "unk");
		verbList.put("marry-VB x-NN off-IN", "unk");
		verbList.put("mask-VB x-NN out-IN", "unk");
		verbList.put("match-VB x-NN up-IN", "unk");
		verbList.put("max-VB x-NN out-IN", "unk");
		verbList.put("melt-VB x-NN down-IN", "unk");
		verbList.put("mess-VB x-NN up-IN", "unk");
		verbList.put("mete-VB x-NN out-IN", "unk");
		verbList.put("miss-VB x-NN out-IN", "unk");
		verbList.put("mix-VB x-NN up-IN", "unk");
		verbList.put("mount-VB x-NN up-IN", "unk");
		verbList.put("move-VB x-NN about-IN", "unk");
		verbList.put("move-VB x-NN in-IN", "unk");
		verbList.put("move-VB x-NN out-IN", "unk");
		verbList.put("muddle-VB x-NN up-IN", "unk");
		verbList.put("mush-VB x-NN together-IN", "unk");
		verbList.put("nail-VB x-NN down-IN", "unk");
		verbList.put("nail-VB x-NN up-IN", "unk");
		verbList.put("narrow-VB x-NN down-IN", "unk");
		verbList.put("nod-VB x-NN off-IN", "unk");
		verbList.put("notch-VB x-NN up-IN", "unk");
		verbList.put("note-VB x-NN down-IN", "unk");
		verbList.put("nudge-VB x-NN up-IN", "unk");
		verbList.put("open-VB x-NN up-IN", "unk");
		verbList.put("pack-VB x-NN in-IN", "unk");
		verbList.put("pack-VB x-NN up-IN", "unk");
		verbList.put("parcel-VB x-NN out-IN", "unk");
		verbList.put("pare-VB x-NN down-IN", "unk");
		verbList.put("pare-VB x-NN off-IN", "unk");
		verbList.put("pass-VB x-NN along-IN", "unk");
		verbList.put("pass-VB x-NN off-IN", "unk");
		verbList.put("pass-VB x-NN on-IN", "unk");
		verbList.put("pass-VB x-NN over-IN", "unk");
		verbList.put("patch-VB x-NN in-IN", "unk");
		verbList.put("patch-VB x-NN up-IN", "unk");
		verbList.put("pay-VB x-NN off-IN", "unk");
		verbList.put("peel-VB x-NN off-IN", "unk");
		verbList.put("pencil-VB x-NN in-IN", "unk");
		verbList.put("phase-VB x-NN in-IN", "unk");
		verbList.put("phase-VB x-NN out-IN", "unk");
		verbList.put("pick-VB x-NN off-IN", "unk");
		verbList.put("pick-VB x-NN out-IN", "unk");
		verbList.put("pick-VB x-NN up-IN", "unk");
		verbList.put("piece-VB x-NN together-IN", "unk");
		verbList.put("pile-VB x-NN up-IN", "unk");
		verbList.put("pin-VB x-NN down-IN", "unk");
		verbList.put("pin-VB x-NN on-IN", "unk");
		verbList.put("pin-VB x-NN up-IN", "unk");
		verbList.put("pipe-VB x-NN in-IN", "unk");
		verbList.put("piss-VB x-NN off-IN", "unk");
		verbList.put("plant-VB x-NN out-IN", "unk");
		verbList.put("pluck-VB x-NN out-IN", "unk");
		verbList.put("pluck-VB x-NN up-IN", "unk");
		verbList.put("plug-VB x-NN in-IN", "unk");
		verbList.put("plunk-VB x-NN down-IN", "unk");
		verbList.put("point-VB x-NN out-IN", "unk");
		verbList.put("polish-VB x-NN off-IN", "unk");
		verbList.put("polish-VB x-NN up-IN", "unk");
		verbList.put("pop-VB x-NN off-IN", "unk");
		verbList.put("pop-VB x-NN out-IN", "unk");
		verbList.put("pop-VB x-NN up-IN", "unk");
		verbList.put("pour-VB x-NN in-IN", "unk");
		verbList.put("pour-VB x-NN off-IN", "unk");
		verbList.put("pour-VB x-NN out-IN", "unk");
		verbList.put("power-VB x-NN down-IN", "unk");
		verbList.put("power-VB x-NN up-IN", "unk");
		verbList.put("press-VB x-NN in-IN", "unk");
		verbList.put("print-VB x-NN out-IN", "unk");
		verbList.put("prop-VB x-NN open-IN", "unk");
		verbList.put("prop-VB x-NN up-IN", "unk");
		verbList.put("psyche-VB x-NN out-IN", "unk");
		verbList.put("psyche-VB x-NN out-IN", "unk");
		verbList.put("pucker-VB x-NN up-IN", "unk");
		verbList.put("pull-VB x-NN across-IN", "unk");
		verbList.put("pull-VB x-NN apart-IN", "unk");
		verbList.put("pull-VB x-NN away-IN", "unk");
		verbList.put("pull-VB x-NN back-IN", "unk");
		verbList.put("pull-VB x-NN down-IN", "unk");
		verbList.put("pull-VB x-NN in-IN", "unk");
		verbList.put("pull-VB x-NN off-IN", "unk");
		verbList.put("pull-VB x-NN open-IN", "unk");
		verbList.put("pull-VB x-NN out-IN", "unk");
		verbList.put("pull-VB x-NN up-IN", "unk");
		verbList.put("pump-VB x-NN in-IN", "unk");
		verbList.put("pump-VB x-NN out-IN", "unk");
		verbList.put("pump-VB x-NN up-IN", "unk");
		verbList.put("push-VB x-NN aside-IN", "unk");
		verbList.put("push-VB x-NN away-IN", "unk");
		verbList.put("push-VB x-NN back-IN", "unk");
		verbList.put("push-VB x-NN down-IN", "unk");
		verbList.put("push-VB x-NN forward-IN", "unk");
		verbList.put("push-VB x-NN in-IN", "unk");
		verbList.put("push-VB x-NN off-IN", "unk");
		verbList.put("push-VB x-NN open-IN", "unk");
		verbList.put("push-VB x-NN up-IN", "unk");
		verbList.put("put-VB x-NN aside-IN", "unk");
		verbList.put("put-VB x-NN away-IN", "unk");
		verbList.put("put-VB x-NN back-IN", "unk");
		verbList.put("put-VB x-NN by-IN", "unk");
		verbList.put("put-VB x-NN down-IN", "unk");
		verbList.put("put-VB x-NN in-IN", "unk");
		verbList.put("put-VB x-NN off-IN", "unk");
		verbList.put("put-VB x-NN on-IN", "unk");
		verbList.put("put-VB x-NN out-IN", "unk");
		verbList.put("put-VB x-NN through-IN", "unk");
		verbList.put("put-VB x-NN together-IN", "unk");
		verbList.put("put-VB x-NN up-IN", "unk");
		verbList.put("puzzle-VB x-NN out-IN", "unk");
		verbList.put("queue-VB x-NN up-IN", "unk");
		verbList.put("rack-VB x-NN up-IN", "unk");
		verbList.put("raise-VB x-NN up-IN", "unk");
		verbList.put("ramp-VB x-NN up-IN", "unk");
		verbList.put("ration-VB x-NN out-IN", "unk");
		verbList.put("read-VB x-NN in-IN", "unk");
		verbList.put("read-VB x-NN off-IN", "unk");
		verbList.put("read-VB x-NN out-IN", "unk");
		verbList.put("reel-VB x-NN in-IN", "unk");
		verbList.put("reel-VB x-NN off-IN", "unk");
		verbList.put("reel-VB x-NN out-IN", "unk");
		verbList.put("rehash-VB x-NN out-IN", "unk");
		verbList.put("rein-VB x-NN in-IN", "unk");
		verbList.put("render-VB x-NN up-IN", "unk");
		verbList.put("rent-VB x-NN out-IN", "unk");
		verbList.put("ride-VB x-NN in-IN", "unk");
		verbList.put("ride-VB x-NN out-IN", "unk");
		verbList.put("ride-VB x-NN up-IN", "unk");
		verbList.put("rig-VB x-NN up-IN", "unk");
		verbList.put("ring-IN", "unk");
		verbList.put("rinse-VB x-NN out-IN", "unk");
		verbList.put("rip-VB x-NN off-IN", "unk");
		verbList.put("rip-VB x-NN up-IN", "unk");
		verbList.put("roar-VB x-NN out-IN", "unk");
		verbList.put("roll-VB x-NN down-IN", "unk");
		verbList.put("roll-VB x-NN out-IN", "unk");
		verbList.put("roll-VB x-NN over-IN", "unk");
		verbList.put("roll-VB x-NN up-IN", "unk");
		verbList.put("root-VB x-NN out-IN", "unk");
		verbList.put("rope-VB x-NN together-IN", "unk");
		verbList.put("rough-VB x-NN in-IN", "unk");
		verbList.put("rough-VB x-NN out-IN", "unk");
		verbList.put("round-VB x-NN down-IN", "unk");
		verbList.put("round-VB x-NN off-IN", "unk");
		verbList.put("round-VB x-NN out-IN", "unk");
		verbList.put("round-VB x-NN up-IN", "unk");
		verbList.put("rub-VB x-NN in-IN", "unk");
		verbList.put("rub-VB x-NN off-IN", "unk");
		verbList.put("rub-VB x-NN out-IN", "unk");
		verbList.put("rule-VB x-NN out-IN", "unk");
		verbList.put("run-VB x-NN off-IN", "unk");
		verbList.put("rush-VB x-NN out-IN", "unk");
		verbList.put("saddle-VB x-NN up-IN", "unk");
		verbList.put("sand-VB x-NN down-IN", "unk");
		verbList.put("sand-VB x-NN off-IN", "unk");
		verbList.put("scale-VB x-NN up-IN", "unk");
		verbList.put("scar-VB x-NN up-IN", "unk");
		verbList.put("scarf-VB x-NN down-IN", "unk");
		verbList.put("schedule-VB x-NN in-IN", "unk");
		verbList.put("schlep-VB x-NN around-IN", "unk");
		verbList.put("scoop-VB x-NN out-IN", "unk");
		verbList.put("scoop-VB x-NN up-IN", "unk");
		verbList.put("scout-VB x-NN out-IN", "unk");
		verbList.put("scrape-VB x-NN away-IN", "unk");
		verbList.put("scrape-VB x-NN off-IN", "unk");
		verbList.put("scrape-VB x-NN out-IN", "unk");
		verbList.put("scrape-VB x-NN together-IN", "unk");
		verbList.put("scrape-VB x-NN up-IN", "unk");
		verbList.put("scratch-IN", "unk");
		verbList.put("screen-VB x-NN out-IN", "unk");
		verbList.put("screw-VB x-NN in-IN", "unk");
		verbList.put("screw-VB x-NN up-IN", "unk");
		verbList.put("scribble-VB x-NN down-IN", "unk");
		verbList.put("scrub-VB x-NN off-IN", "unk");
		verbList.put("scrub-VB x-NN out-IN", "unk");
		verbList.put("scrunch-VB x-NN up-IN", "unk");
		verbList.put("seal-VB x-NN in-IN", "unk");
		verbList.put("seal-VB x-NN off-IN", "unk");
		verbList.put("seal-VB x-NN out-IN", "unk");
		verbList.put("seal-VB x-NN up-IN", "unk");
		verbList.put("search-VB x-NN out-IN", "unk");
		verbList.put("seek-VB x-NN out-IN", "unk");
		verbList.put("sell-VB x-NN off-IN", "unk");
		verbList.put("sell-VB x-NN out-IN", "unk");
		verbList.put("send-VB x-NN back-IN", "unk");
		verbList.put("send-VB x-NN in-IN", "unk");
		verbList.put("send-VB x-NN off-IN", "unk");
		verbList.put("send-VB x-NN out-IN", "unk");
		verbList.put("separate-VB x-NN out-IN", "unk");
		verbList.put("set-VB x-NN apart-IN", "unk");
		verbList.put("set-VB x-NN aside-IN", "unk");
		verbList.put("set-VB x-NN forth-IN", "unk");
		verbList.put("set-VB x-NN off-IN", "unk");
		verbList.put("set-VB x-NN up-IN", "unk");
		verbList.put("settle-VB x-NN down-IN", "unk");
		verbList.put("shack-VB x-NN up-IN", "unk");
		verbList.put("shake-VB x-NN off-IN", "unk");
		verbList.put("shake-VB x-NN out-IN", "unk");
		verbList.put("shake-VB x-NN up-IN", "unk");
		verbList.put("sharpen-VB x-NN up-IN", "unk");
		verbList.put("shave-VB x-NN off-IN", "unk");
		verbList.put("shell-VB x-NN out-IN", "unk");
		verbList.put("ship-VB x-NN back-IN", "unk");
		verbList.put("ship-VB x-NN out-IN", "unk");
		verbList.put("shoo-VB x-NN away-IN", "unk");
		verbList.put("shoot-VB x-NN down-IN", "unk");
		verbList.put("shoot-VB x-NN off-IN", "unk");
		verbList.put("shoot-VB x-NN up-IN", "unk");
		verbList.put("shop-VB x-NN around-IN", "unk");
		verbList.put("short-VB x-NN out-IN", "unk");
		verbList.put("shout-VB x-NN back-IN", "unk");
		verbList.put("shout-VB x-NN out-IN", "unk");
		verbList.put("shovel-VB x-NN out-IN", "unk");
		verbList.put("shrug-VB x-NN off-IN", "unk");
		verbList.put("shut-VB x-NN down-IN", "unk");
		verbList.put("shut-VB x-NN off-IN", "unk");
		verbList.put("shut-VB x-NN out-IN", "unk");
		verbList.put("shut-VB x-NN up-IN", "unk");
		verbList.put("sign-VB x-NN up-IN", "unk");
		verbList.put("single-VB x-NN out-IN", "unk");
		verbList.put("sit-VB x-NN out-IN", "unk");
		verbList.put("size-VB x-NN up-IN", "unk");
		verbList.put("slam-VB x-NN down-IN", "unk");
		verbList.put("slam-VB x-NN on-IN", "unk");
		verbList.put("slap-VB x-NN down-IN", "unk");
		verbList.put("slap-VB x-NN on-IN", "unk");
		verbList.put("sleep-VB x-NN off-IN", "unk");
		verbList.put("slice-VB x-NN off-IN", "unk");
		verbList.put("slice-VB x-NN out-IN", "unk");
		verbList.put("slice-VB x-NN up-IN", "unk");
		verbList.put("slim-VB x-NN down-IN", "unk");
		verbList.put("slip-VB x-NN in-IN", "unk");
		verbList.put("slip-VB x-NN off-IN", "unk");
		verbList.put("slip-VB x-NN on-IN", "unk");
		verbList.put("slough-VB x-NN off-IN", "unk");
		verbList.put("slow-VB x-NN down-IN", "unk");
		verbList.put("slug-VB x-NN down-IN", "unk");
		verbList.put("slurp-VB x-NN up-IN", "unk");
		verbList.put("smash-VB x-NN in-IN", "unk");
		verbList.put("smash-VB x-NN up-IN", "unk");
		verbList.put("smooth-VB x-NN away-IN", "unk");
		verbList.put("smooth-VB x-NN out-IN", "unk");
		verbList.put("smuggle-VB x-NN in-IN", "unk");
		verbList.put("smuggle-VB x-NN out-IN", "unk");
		verbList.put("snap-VB x-NN in-IN", "unk");
		verbList.put("snap-VB x-NN off-IN", "unk");
		verbList.put("snap-VB x-NN up-IN", "unk");
		verbList.put("snatch-VB x-NN up-IN", "unk");
		verbList.put("sniff-VB x-NN out-IN", "unk");
		verbList.put("soak-VB x-NN in-IN", "unk");
		verbList.put("soak-VB x-NN up-IN", "unk");
		verbList.put("soap-VB x-NN up-IN", "unk");
		verbList.put("sober-VB x-NN up-IN", "unk");
		verbList.put("sock-VB x-NN in-IN", "unk");
		verbList.put("soften-VB x-NN up-IN", "unk");
		verbList.put("sop-VB x-NN up-IN", "unk");
		verbList.put("sort-VB x-NN out-IN", "unk");
		verbList.put("sound-VB x-NN out-IN", "unk");
		verbList.put("space-VB x-NN out-IN", "unk");
		verbList.put("spark-VB x-NN off-IN", "unk");
		verbList.put("speed-VB x-NN up-IN", "unk");
		verbList.put("spell-VB x-NN out-IN", "unk");
		verbList.put("spin-VB x-NN out-IN", "unk");
		verbList.put("spirit-VB x-NN away-IN", "unk");
		verbList.put("spit-VB x-NN out-IN", "unk");
		verbList.put("split-VB x-NN off-IN", "unk");
		verbList.put("split-VB x-NN up-IN", "unk");
		verbList.put("spread-VB x-NN out-IN", "unk");
		verbList.put("spruce-VB x-NN up-IN", "unk");
		verbList.put("spur-VB x-NN on-IN", "unk");
		verbList.put("square-VB x-NN away-IN", "unk");
		verbList.put("square-VB x-NN up-IN", "unk");
		verbList.put("squeeze-VB x-NN in-IN", "unk");
		verbList.put("squeeze-VB x-NN out-IN", "unk");
		verbList.put("squirrel-VB x-NN away-IN", "unk");
		verbList.put("stack-VB x-NN up-IN", "unk");
		verbList.put("stall-VB x-NN off-IN", "unk");
		verbList.put("stamp-VB x-NN on-IN", "unk");
		verbList.put("stamp-VB x-NN out-IN", "unk");
		verbList.put("stand-VB x-NN up-IN", "unk");
		verbList.put("start-VB x-NN off-IN", "unk");
		verbList.put("start-VB x-NN out-IN", "unk");
		verbList.put("start-VB x-NN over-IN", "unk");
		verbList.put("start-VB x-NN up-IN", "unk");
		verbList.put("stash-VB x-NN away-IN", "unk");
		verbList.put("stave-VB x-NN off-IN", "unk");
		verbList.put("steal-VB x-NN away-IN", "unk");
		verbList.put("steam-VB x-NN open-IN", "unk");
		verbList.put("step-VB x-NN up-IN", "unk");
		verbList.put("stick-VB x-NN out-IN", "unk");
		verbList.put("stick-VB x-NN up-IN", "unk");
		verbList.put("stiffen-VB x-NN up-IN", "unk");
		verbList.put("stink-VB x-NN up-IN", "unk");
		verbList.put("stir-VB x-NN in-IN", "unk");
		verbList.put("stir-VB x-NN up-IN", "unk");
		verbList.put("store-VB x-NN up-IN", "unk");
		verbList.put("straighten-VB x-NN out-IN", "unk");
		verbList.put("straighten-VB x-NN up-IN", "unk");
		verbList.put("strap-VB x-NN up-IN", "unk");
		verbList.put("strike-VB x-NN down-IN", "unk");
		verbList.put("strike-VB x-NN off-IN", "unk");
		verbList.put("strike-VB x-NN out-IN", "unk");
		verbList.put("string-IN", "unk");
		verbList.put("string-IN", "unk");
		verbList.put("string-IN", "unk");
		verbList.put("string-IN", "unk");
		verbList.put("strip-VB x-NN off-IN", "unk");
		verbList.put("stub-VB x-NN out-IN", "unk");
		verbList.put("suck-VB x-NN in-IN", "unk");
		verbList.put("suck-VB x-NN out-IN", "unk");
		verbList.put("suck-VB x-NN up-IN", "unk");
		verbList.put("sum-VB x-NN up-IN", "unk");
		verbList.put("summon-VB x-NN up-IN", "unk");
		verbList.put("swallow-VB x-NN down-IN", "unk");
		verbList.put("swallow-VB x-NN up-IN", "unk");
		verbList.put("swear-VB x-NN in-IN", "unk");
		verbList.put("sweat-VB x-NN off-IN", "unk");
		verbList.put("sweat-VB x-NN out-IN", "unk");
		verbList.put("sweep-VB x-NN away-IN", "unk");
		verbList.put("sweep-VB x-NN up-IN", "unk");
		verbList.put("switch-VB x-NN off-IN", "unk");
		verbList.put("switch-VB x-NN on-IN", "unk");
		verbList.put("swoop-VB x-NN up-IN", "unk");
		verbList.put("tack-VB x-NN on-IN", "unk");
		verbList.put("tack-VB x-NN up-IN", "unk");
		verbList.put("take-VB x-NN aback-IN", "unk");
		verbList.put("take-VB x-NN along-IN", "unk");
		verbList.put("take-VB x-NN apart-IN", "unk");
		verbList.put("take-VB x-NN away-IN", "unk");
		verbList.put("take-VB x-NN back-IN", "unk");
		verbList.put("take-VB x-NN down-IN", "unk");
		verbList.put("take-VB x-NN home-IN", "unk");
		verbList.put("take-VB x-NN in-IN", "unk");
		verbList.put("take-VB x-NN off-IN", "unk");
		verbList.put("take-VB x-NN on-IN", "unk");
		verbList.put("take-VB x-NN out-IN", "unk");
		verbList.put("take-VB x-NN over-IN", "unk");
		verbList.put("take-VB x-NN up-IN", "unk");
		verbList.put("talk-VB x-NN over-IN", "unk");
		verbList.put("tangle-VB x-NN up-IN", "unk");
		verbList.put("tank-VB x-NN up-IN", "unk");
		verbList.put("tap-VB x-NN off-IN", "unk");
		verbList.put("tear-VB x-NN apart-IN", "unk");
		verbList.put("tear-VB x-NN off-IN", "unk");
		verbList.put("tear-VB x-NN open-IN", "unk");
		verbList.put("tear-VB x-NN up-IN", "unk");
		verbList.put("tease-VB x-NN apart-IN", "unk");
		verbList.put("tease-VB x-NN open-IN", "unk");
		verbList.put("tease-VB x-NN out-IN", "unk");
		verbList.put("tee-VB x-NN off-IN", "unk");
		verbList.put("tense-VB x-NN up-IN", "unk");
		verbList.put("thin-VB x-NN out-IN", "unk");
		verbList.put("think-VB x-NN through-IN", "unk");
		verbList.put("think-VB x-NN up-IN", "unk");
		verbList.put("throttle-VB x-NN back-IN", "unk");
		verbList.put("throw-VB x-NN away-IN", "unk");
		verbList.put("throw-VB x-NN in-IN", "unk");
		verbList.put("throw-VB x-NN open-IN", "unk");
		verbList.put("throw-VB x-NN out-IN", "unk");
		verbList.put("throw-VB x-NN over-IN", "unk");
		verbList.put("throw-VB x-NN up-IN", "unk");
		verbList.put("thrust-VB x-NN out-IN", "unk");
		verbList.put("tick-VB x-NN off-IN", "unk");
		verbList.put("tidy-VB x-NN up-IN", "unk");
		verbList.put("tie-VB x-NN in-IN", "unk");
		verbList.put("tie-VB x-NN on-IN", "unk");
		verbList.put("tie-VB x-NN up-IN", "unk");
		verbList.put("tighten-VB x-NN up-IN", "unk");
		verbList.put("tip-VB x-NN off-IN", "unk");
		verbList.put("tip-VB x-NN over-IN", "unk");
		verbList.put("tire-VB x-NN out-IN", "unk");
		verbList.put("tone-VB x-NN down-IN", "unk");
		verbList.put("toss-VB x-NN away-IN", "unk");
		verbList.put("total-VB x-NN up-IN", "unk");
		verbList.put("touch-VB x-NN off-IN", "unk");
		verbList.put("towel-VB x-NN off-IN", "unk");
		verbList.put("trace-VB x-NN back-IN", "unk");
		verbList.put("trace-VB x-NN down-IN", "unk");
		verbList.put("track-VB x-NN down-IN", "unk");
		verbList.put("trade-VB x-NN in-IN", "unk");
		verbList.put("trim-VB x-NN away-IN", "unk");
		verbList.put("trim-VB x-NN down-IN", "unk");
		verbList.put("trim-VB x-NN off-IN", "unk");
		verbList.put("truss-VB x-NN up-IN", "unk");
		verbList.put("try-VB x-NN out-IN", "unk");
		verbList.put("tuck-VB x-NN in-IN", "unk");
		verbList.put("tune-VB x-NN in-IN", "unk");
		verbList.put("tune-VB x-NN out-IN", "unk");
		verbList.put("tune-VB x-NN up-IN", "unk");
		verbList.put("turn-VB x-NN back-IN", "unk");
		verbList.put("turn-VB x-NN down-IN", "unk");
		verbList.put("turn-VB x-NN in-IN", "unk");
		verbList.put("turn-VB x-NN off-IN", "unk");
		verbList.put("turn-VB x-NN on-IN", "unk");
		verbList.put("turn-VB x-NN out-IN", "unk");
		verbList.put("turn-VB x-NN over-IN", "unk");
		verbList.put("turn-VB x-NN up-IN", "unk");
		verbList.put("type-VB x-NN in-IN", "unk");
		verbList.put("type-VB x-NN out-IN", "unk");
		verbList.put("type-VB x-NN up-IN", "unk");
		verbList.put("use-VB x-NN up-IN", "unk");
		verbList.put("usher-VB x-NN in-IN", "unk");
		verbList.put("vomit-VB x-NN up-IN", "unk");
		verbList.put("wake-VB x-NN x-VB x-NN up-IN", "unk");
		verbList.put("wall-VB x-NN in-IN", "unk");
		verbList.put("wall-VB x-NN off-IN", "unk");
		verbList.put("want-VB x-NN back-IN", "unk");
		verbList.put("ward-VB x-NN off-IN", "unk");
		verbList.put("warm-VB x-NN up-IN", "unk");
		verbList.put("wash-VB x-NN away-IN", "unk");
		verbList.put("wash-VB x-NN down-IN", "unk");
		verbList.put("wash-VB x-NN out-IN", "unk");
		verbList.put("wash-VB x-NN up-IN", "unk");
		verbList.put("wear-VB x-NN away-IN", "unk");
		verbList.put("wear-VB x-NN out-IN", "unk");
		verbList.put("wedge-VB x-NN in-IN", "unk");
		verbList.put("weed-VB x-NN out-IN", "unk");
		verbList.put("weigh-VB x-NN down-IN", "unk");
		verbList.put("weigh-VB x-NN up-IN", "unk");
		verbList.put("wheel-VB x-NN in-IN", "unk");
		verbList.put("wheel-VB x-NN out-IN", "unk");
		verbList.put("whip-VB x-NN in-IN", "unk");
		verbList.put("whip-VB x-NN off-IN", "unk");
		verbList.put("whip-VB x-NN out-IN", "unk");
		verbList.put("whisk-VB x-NN away-IN", "unk");
		verbList.put("whistle-VB x-NN up-IN", "unk");
		verbList.put("winch-VB x-NN in-IN", "unk");
		verbList.put("winch-VB x-NN up-IN", "unk");
		verbList.put("wind-VB x-NN down-IN", "unk");
		verbList.put("wind-VB x-NN up-IN", "unk");
		verbList.put("winnow-VB x-NN out-IN", "unk");
		verbList.put("wipe-VB x-NN off-IN", "unk");
		verbList.put("wipe-VB x-NN out-IN", "unk");
		verbList.put("wipe-VB x-NN up-IN", "unk");
		verbList.put("wolf-VB x-NN down-IN", "unk");
		verbList.put("work-VB x-NN in-IN", "unk");
		verbList.put("work-VB x-NN out-IN", "unk");
		verbList.put("wrap-VB x-NN up-IN", "unk");
		verbList.put("wrest-VB x-NN away-IN", "unk");
		verbList.put("wring-VB x-NN out-IN", "unk");
		verbList.put("write-VB x-NN back-IN", "unk");
		verbList.put("write-VB x-NN down-IN", "unk");
		verbList.put("write-VB x-NN in-IN", "unk");
		verbList.put("write-VB x-NN off-IN", "unk");
		verbList.put("write-VB x-NN out-IN", "unk");
		verbList.put("write-VB x-NN up-IN", "unk");
		verbList.put("yield-VB x-NN up-IN", "unk");
	}
}
